/**
 * Add-ons: eyebrows, eyelashes, facial hair and glasses, all generated by the pipeline (brow_strands.py, lash_strands.py,
 * beard_strands.py, stubble.py, glasses_gen.py), one file per style under /models/addons/<category>/ and one index.json
 * per category. The loader is hair.ts in small: a style is fetched the first time it is chosen and attached under the
 * head's root node. Brows, lashes and strand beards are strands (lib/groom.ts) whose roots follow the skin every frame,
 * so they follow the sliders, blink and speak with it; stubble lives in the skin shader and short beards are shells
 * (lib/beardShells.ts); glasses are a .glb with the identity targets only (they are rigid). The previous style of a
 * category is disposed when the next one is attached.
 *
 * Colour: brows, lashes and beards wear the hair colour (Natural = their own colours, except that a beard matches the
 * hair style's own colour, see ADDONS.matchNaturalHair); facial hair can have a colour of its own.
 * Glasses keep their painted frame and get a see-through lens.
 *
 * Everything here is part of the character: it is in the screenshot sent to Claude and in the
 * look that travels with the design request (lib/look.ts). Nothing is ever hidden for a capture.
 */
import { Color, DoubleSide, Group, LinearSRGBColorSpace, MeshPhysicalMaterial, type MeshStandardMaterial, type Object3D } from "three";

import { NATURAL_HAIR } from "@/lib/swatches";
import { skinRig } from "@/lib/skin";
import { skinSurface } from "@/lib/skinSurface";
import { disableStubble, enableStubble, skinUniforms } from "@/lib/skinShader";
import { loadKtx2, TEXTURES_BASE } from "@/lib/textures";
import { fitGlasses } from "@/lib/glassesFit";
import { ADDON_CATEGORIES, addonIndex, MODELS_BASE, type AddonCategory, type AddonStyleDef, type GlassesLook } from "@/lib/data";
import { partDone, prefetchPart, takePrefetched } from "@/lib/headLoad";
import { finishPieceFade, swapPiece } from "@/lib/pieceFade";
import {
  disposePiece,
  gltfLoader,
  HAIR_COLOURS,
  hairChipHex,
  hairColourById,
  hairState,
  hairStyleById,
  meshesOf,
  blendStrands,
  mixHex,
  naturalHex,
  onHairChange,
  rampOf,
  strandColours,
  tintStrands,
  type HairColourId,
  type HairSnapshot,
  type StrandColours,
  type StrandRamp,
} from "@/lib/hair";
import { morphs } from "@/lib/morphs/store";
import { installMorph } from "@/lib/morphShader";

export { ADDON_CATEGORIES, type AddonCategory };

/**
 * Every add-on tunable, per category.
 * `label`   the row's name in the panel.
 * `darken`  0..1, how far a swatch is taken toward `darkenToward`: brows read a shade darker
 *           than the hair in the hair's own hue ("shadow" = the swatch's shadow colour; toward
 *           black a blonde brow turns olive), lashes stay dark even on white hair ("black").
 *           A style may set its own (GroomDef.darken).
 * `matchNaturalHair`  what "same as hair" means while the hair wears Natural: the add-on is
 *           tinted with the hair style's own colour, mixed toward black by `shadow` and toward
 *           white by `highlight`, so it matches the head. false: it keeps its own colours.
 *           The beard's own Natural swatch still shows its own colours.
 */
export const ADDONS = {
  // brows are solid strands: a light darken, or they go black
  eyebrows: { label: "Eyebrows", darken: 0.15, darkenToward: "shadow", matchNaturalHair: { shadow: 0.3, highlight: 0.1 } },
  // lashes take the swatch much darker, or they read brown
  eyelashes: { label: "Eyelashes", darken: 0.9, darkenToward: "black", matchNaturalHair: { shadow: 0.92, highlight: 0 } },
  // A dark beard keeps its strands: a little more highlight in the matched ramp.
  facialHair: { label: "Facial hair", darken: 0, darkenToward: "black", matchNaturalHair: { shadow: 0.6, highlight: 0.35 } },
  glasses: { label: "Glasses", darken: 0, darkenToward: "black", matchNaturalHair: false },
} as const satisfies Record<
  AddonCategory,
  { label: string; darken: number; darkenToward: "black" | "shadow"; matchNaturalHair: false | { shadow: number; highlight: number } }
>;

/**
 * Glasses (pipeline glasses_gen.py): the frame keeps the file's colour and metal/roughness maps, and acetate gets a
 * lacquer coat; the lens takes its tint and opacity from the style (index.json `glasses.lens`). The file holds only the
 * front wall of each lens (the pipeline drops the back wall), so the tint is one layer in one draw call. Clear glass
 * reads through its reflection, not through a haze: low opacity, a strong environment.
 */
export const GLASSES_MATERIAL = {
  acetate: { clearcoat: 0.8, clearcoatRoughness: 0.06, envMapIntensity: 1.2 },
  metal: { envMapIntensity: 1.4 },
  lens: { roughness: 0.05, envMapIntensity: 1.8 },
  // Glass shows mostly as reflection: the lens's alpha grows with what it reflects (glare), so a clear lens is nearly
  // invisible face-on and bright where it catches a light; `gradient` clears the lower half of graded sunglasses.
  glare: 1.2,
  mirror: { metalness: 0.9, roughness: 0.08 }, // at mirror 1 (blended in by the style's mirror value)
  lensRenderOrder: 2, // after the skin, the strands and the shell beards (1)
};

const STORAGE_KEY = "ftv-addons"; // sessionStorage: kept across reloads, but a new tab opens on the blank head

export type AddonStyle = "none" | (string & {});
/** "hair" = wear the hair colour (the default), or a swatch of its own. */
export type FacialHairColour = "hair" | HairColourId;

export const addonStyles = (category: AddonCategory): readonly AddonStyleDef[] => addonIndex[category].styles;
export const addonStyleById = (category: AddonCategory, id: string): AddonStyleDef | undefined => addonIndex[category].styles.find((s) => s.id === id);

type Styles = Record<AddonCategory, AddonStyle>;
const perCategory = <T>(value: (category: AddonCategory) => T) => Object.fromEntries(ADDON_CATEGORIES.map((c) => [c, value(c)])) as Record<AddonCategory, T>;

/**
 * What a first visit shows: a blank head, no brows, lashes, beard or glasses (Reset uses it too). Also what the server
 * renders.
 */
export const ADDON_DEFAULTS: Styles & { facialHairColour: FacialHairColour } = {
  ...perCategory(() => "none" as AddonStyle),
  facialHairColour: "hair",
};
export const addonState = { ...ADDON_DEFAULTS };

export const addonRig = {
  /** What is on the head per category: the style's node (userData.style = its id). */
  meshes: perCategory(() => null as Object3D | null),
  /** True while a category's style is on its way. */
  loading: perCategory(() => false),
  /** The head's root node, set by Head.tsx. */
  parent: null as Object3D | null,
};

// --- UI sync (useSyncExternalStore in AddonControls) ------------------------------------------

export type AddonSnapshot = Styles & { facialHairColour: FacialHairColour; loading: Record<AddonCategory, boolean> };
export const ADDON_SERVER_SNAPSHOT: AddonSnapshot = { ...ADDON_DEFAULTS, loading: perCategory(() => false) };
let snapshot = ADDON_SERVER_SNAPSHOT;

const listeners = new Set<() => void>();
export function onAddonChange(fn: () => void): () => void {
  listeners.add(fn);
  return () => {
    listeners.delete(fn);
  };
}
/** Immutable snapshot for React. Restores the saved choice on first use. */
export function addonSnapshot(): AddonSnapshot {
  loadAddonState();
  return snapshot;
}
const notify = () => {
  snapshot = { ...addonState, loading: { ...addonRig.loading } };
  for (const fn of listeners) fn();
};

let loaded = false;
/** Restore the last choice (idempotent; safe without a window). Unknown ids fall back to the default. */
function loadAddonState(): void {
  if (loaded) return;
  loaded = true;
  try {
    const raw = typeof window !== "undefined" ? window.sessionStorage.getItem(STORAGE_KEY) : null;
    if (!raw) return;
    const saved = JSON.parse(raw) as Partial<typeof addonState>;
    for (const c of ADDON_CATEGORIES) {
      const id = saved[c];
      if (id === "none" || (typeof id === "string" && addonStyleById(c, id))) addonState[c] = id;
    }
    if (saved.facialHairColour === "hair" || HAIR_COLOURS.some((c) => c.id === saved.facialHairColour)) addonState.facialHairColour = saved.facialHairColour as FacialHairColour;
  } catch {
    /* private mode or malformed: keep defaults */
  }
  notify();
}

function persist(): void {
  try {
    window.sessionStorage.setItem(STORAGE_KEY, JSON.stringify(addonState));
  } catch {
    /* private mode: nothing to do */
  }
}

// --- colour -------------------------------------------------------------------------------------

/** The swatch a category wears: the hair's, unless facial hair has its own. */
function addonColour(category: AddonCategory): HairColourId {
  return category === "facialHair" && addonState.facialHairColour !== "hair" ? addonState.facialHairColour : hairState.colour;
}

/**
 * Push the current colours onto everything attached (runs on every hair colour change too; `seconds` > 0 blends).
 * `only` limits it to one category, so attaching a beard doesn't cut short the brows' colour blend.
 */
export function applyAddons(seconds = 0, only?: AddonCategory): void {
  for (const c of only ? [only] : ADDON_CATEGORIES) {
    const node = addonRig.meshes[c];
    const colours = node?.userData.colours as StrandColours | undefined;
    if (!node || !colours) continue; // nothing attached, or glasses
    const style = addonStyleById(c, node.userData.style as string);
    // Natural is the style's own root → tip ramp. A strand style darkens it like any colour; a stubble or shell stand-in
    // goes back to exactly the colours it was filled with (standIn), so Natural after a swatch restores them.
    const def: (typeof ADDONS)[AddonCategory] = ADDONS[c];
    const chosen = addonRamp(c);
    const own = style?.strands ?? style?.stubble ?? style?.shells;
    const ramp = chosen ?? (own ? { shadow: own.root, highlight: own.tip } : null);
    // (a strand style may set its own: fair lashes follow the hair colour closely, lash extensions are always black)
    const darken = !chosen && !style?.strands ? 0 : (style?.strands?.darken ?? def.darken);
    const args = [ramp, darken, def.darkenToward] as const;
    if (seconds > 0) blendStrands(colours, seconds, ...args);
    else tintStrands(colours, ...args);
  }
}

const hex = (n: number) => "#" + n.toString(16).padStart(6, "0");

/** The ramp a category renders with (null = its own painted colours); see ADDONS.matchNaturalHair. */
function addonRamp(category: AddonCategory): StrandRamp {
  const ramp = rampOf(hairColourById(addonColour(category)));
  const match = ADDONS[category].matchNaturalHair;
  const followsHair = category !== "facialHair" || addonState.facialHairColour === "hair";
  const hair = hairStyleById(hairState.style);
  if (ramp || !match || !followsHair || !hair) return ramp;
  return { shadow: hex(mixHex(hair.natural, "#000000", match.shadow)), highlight: hex(mixHex(hair.natural, "#ffffff", match.highlight)) };
}

/** Chip colour of a facial hair swatch: "hair" shows the hair's chip, Natural the beard's own painted colour.
 *  Reads the React snapshots, not the live state, so the server render and hydration agree. */
export function facialHairChipHex(colour: FacialHairColour, hair: HairSnapshot, addons: AddonSnapshot): string {
  if (colour === "hair") return hairChipHex(hair.colour, hair.style);
  if (colour !== "natural") return hairColourById(colour).hex;
  return naturalHex(addonStyleById("facialHair", addons.facialHair)?.natural ?? NATURAL_HAIR.hex);
}

// --- loading ------------------------------------------------------------------------------------

/** Glasses: the file's materials rebuilt for the style's look. The lens is the primitive whose material is "glasses_lens". */
function dressGlasses(node: Object3D, look: GlassesLook): void {
  for (const mesh of meshesOf(node)) {
    const material = mesh.material as MeshStandardMaterial;
    const dressed = glassesMaterial(material, look);
    mesh.material = dressed;
    material.dispose();
    if (material.name === "glasses_lens") mesh.renderOrder = GLASSES_MATERIAL.lensRenderOrder;
    installMorph(dressed, "piece"); // grows out of the loader's bubble (lib/morphShader.ts)
  }
}

/** A frame or lens: MeshPhysicalMaterial (lacquered acetate, real metal, glass that shows as reflection). */
function glassesMaterial(src: MeshStandardMaterial, look: GlassesLook): MeshPhysicalMaterial {
  const G = GLASSES_MATERIAL;
  if (src.name !== "glasses_lens") {
    return new MeshPhysicalMaterial({
      name: src.name, map: src.map, metalnessMap: src.metalnessMap, roughnessMap: src.roughnessMap, metalness: 1, roughness: 1,
      ...(look.acetate ? G.acetate : { clearcoat: 0 }), envMapIntensity: look.acetate ? G.acetate.envMapIntensity : G.metal.envMapIntensity,
    });
  }
  const { tint, opacity, gradient, mirror } = look.lens;
  const m = new MeshPhysicalMaterial({
    name: src.name, color: new Color(tint), opacity, transparent: true, depthWrite: false, side: DoubleSide, forceSinglePass: true,
    roughness: G.lens.roughness + (G.mirror.roughness - G.lens.roughness) * mirror, metalness: G.mirror.metalness * mirror,
    envMapIntensity: G.lens.envMapIntensity,
  });
  m.defines = { USE_UV: "" };
  m.onBeforeCompile = (shader) => {
    shader.uniforms.uGlare = { value: G.glare };
    shader.uniforms.uGradient = { value: gradient };
    shader.fragmentShader = "uniform float uGlare, uGradient;\n" + shader.fragmentShader.replace(
      "#include <opaque_fragment>",
      `float glare = dot(reflectedLight.directSpecular + reflectedLight.indirectSpecular, vec3(0.3333));
      diffuseColor.a = clamp(diffuseColor.a * (1.0 - uGradient * smoothstep(0.25, 0.9, vUv.y)) + glare * uGlare, 0.0, 1.0);
      #include <opaque_fragment>`,
    );
  };
  m.customProgramCacheKey = () => "glasses-lens-v1";
  return m;
}

/**
 * The empty stand-in the add-on machinery attaches for a style drawn by the skin (stubble, shell beards). It carries the
 * colour set, filled with the style's own root and tip colours (raw sRGB, as tintStrands writes them) and tinted like
 * strands by applyAddons.
 */
function standIn(category: AddonCategory, style: AddonStyleDef, look: { root: string; tip: string }): { group: Group; colours: StrandColours } {
  const colours = strandColours();
  colours.uniforms.uHairShadow.value.setHex(Number.parseInt(look.root.slice(1), 16), LinearSRGBColorSpace);
  colours.uniforms.uHairHighlight.value.setHex(Number.parseInt(look.tip.slice(1), 16), LinearSRGBColorSpace);
  const group = new Group();
  group.name = category;
  group.userData.style = style.id;
  group.userData.colours = colours;
  return { group, colours };
}

/**
 * A stubble or shell mask's early download (prefetchAddons, Random character's preload), if there is one: its loader
 * reads the file by URL (the HTTP cache has it then), so the bytes are only taken to be freed, once they are in (no
 * second fetch meanwhile). A failed early download: the loader reports it.
 */
const earlyMask = (url: string): Promise<unknown> | undefined => takePrefetched(url)?.catch(() => {});

/**
 * A stubble style (pipeline stubble.py): nothing to draw of its own, it switches the skin shader's stubble on with its
 * coverage mask (lib/skinShader.ts), so it is the skin and follows the jaw and lips everywhere. Its stand-in switches
 * the stubble off again when it is removed (disposePiece → userData.dispose).
 */
async function loadStubble(category: AddonCategory, style: AddonStyleDef, look: NonNullable<AddonStyleDef["stubble"]>, signal: AbortSignal): Promise<Object3D> {
  const early = earlyMask(MODELS_BASE + style.file);
  if (early) await early;
  const [mask, detail] = await Promise.all([loadKtx2(MODELS_BASE + style.file), loadKtx2(TEXTURES_BASE + "stubble_detail.ktx2")]);
  signal.throwIfAborted(); // superseded: the skin is the newer style's now
  const { group, colours } = standIn(category, style, look);
  const material = skinRig.material;
  if (material) enableStubble(material, mask, detail, look, colours.uniforms.uHairShadow.value);
  // only if this stubble is still the one on the skin (a newer stubble style may have replaced it already)
  const skinOff = () => {
    if (skinUniforms.uStubbleColour.value === colours.uniforms.uHairShadow.value) disableStubble(skinRig.material);
  };
  group.userData.skinOff = skinOff;
  group.userData.dispose = skinOff;
  return group;
}

/**
 * A short beard drawn as shells (lib/beardShells.ts) over a light stubble shadow (the skin shader) on the same mask.
 * Like stubble, the returned group is an empty stand-in that carries the colour set and the teardown.
 */
async function loadShells(category: AddonCategory, style: AddonStyleDef, look: NonNullable<AddonStyleDef["shells"]>, signal: AbortSignal): Promise<Object3D> {
  const early = earlyMask(MODELS_BASE + style.file);
  if (early) await early;
  const [{ loadShellMask, mountShells }, detail] = await Promise.all([import("@/lib/beardShells"), loadKtx2(TEXTURES_BASE + "stubble_detail.ktx2")]);
  const mask = await loadShellMask(MODELS_BASE + style.file, signal);
  signal.throwIfAborted(); // superseded: the skin and its shells are the newer style's now
  const { group, colours } = standIn(category, style, look);
  const root = colours.uniforms.uHairShadow.value, tip = colours.uniforms.uHairHighlight.value;
  const material = skinRig.material;
  if (material) enableStubble(material, mask.texture, detail, { length: 0.25, shadow: look.shadow }, root);
  const shells = skinSurface.mesh ? mountShells(skinSurface.mesh, mask, look, { root, tip }) : null;
  if (shells) group.userData.fadeAlso = [shells.mesh]; // drawn under the skin, but cross-fades with this piece (lib/pieceFade.ts)
  const skinOff = () => {
    if (skinUniforms.uStubbleColour.value === root) disableStubble(skinRig.material);
  };
  group.userData.skinOff = skinOff;
  group.userData.dispose = () => {
    shells?.teardown();
    skinOff();
  };
  return group;
}

/**
 * A strand beard's stubble (pipeline beard_strands.py): the skin under the beard and along its faded outline takes the
 * stubble shader on the beard's mask, tinted with the beard's root colour (by reference: recolours follow), so the
 * skin between the hairs is never bare. Chained onto the groom's own teardown.
 */
function underStubble(group: Object3D, maskFile: string, look: NonNullable<AddonStyleDef["stubble"]>, colour: Color): void {
  const groomDispose = group.userData.dispose as (() => void) | undefined;
  let removed = false;
  const skinOff = () => {
    removed = true; // a mask still loading stays off
    if (skinUniforms.uStubbleColour.value === colour) disableStubble(skinRig.material);
  };
  group.userData.skinOff = skinOff;
  group.userData.dispose = () => {
    groomDispose?.();
    skinOff();
  };
  void Promise.all([loadKtx2(MODELS_BASE + maskFile), loadKtx2(TEXTURES_BASE + "stubble_detail.ktx2")])
    .then(([mask, detail]) => {
      if (!removed && skinRig.material) enableStubble(skinRig.material, mask, detail, look, colour);
    })
    .catch((err: unknown) => console.error("addons: failed to load", maskFile, err)); // the beard stays, without its stubble
}

/** Fetch a style's file (abortable) and return its node (named after the category), dressed and ready to attach. */
async function loadAddon(category: AddonCategory, style: AddonStyleDef, signal: AbortSignal): Promise<Object3D> {
  if (style.kind === "stubble" && style.stubble) return loadStubble(category, style, style.stubble, signal);
  if (style.kind === "shells" && style.shells) return loadShells(category, style, style.shells, signal);
  const url = MODELS_BASE + style.file;
  // The first visit's styles were already fetched at hydration (prefetchAddons); everything else fetches now.
  const download =
    takePrefetched(url) ??
    fetch(url, { signal }).then((r) => {
      if (!r.ok) throw new Error(`${r.status} ${r.statusText}`); // never hand a 404 page to the decoder
      return r.arrayBuffer();
    });
  if (style.kind === "strands" && style.strands) {
    // Strand brows, lashes and beards (pipeline brow_strands.py, lash_strands.py, beard_strands.py): drawn by
    // lib/groom.ts, roots follow the face every frame.
    const lidUrl = style.strands.lidFix ? MODELS_BASE + style.strands.lidFix.file : null;
    const [{ buildGroom }, buffer, lidFix] = await Promise.all([
      import("@/lib/groom"),
      download,
      lidUrl ? fetch(lidUrl, { signal }).then((r) => (r.ok ? r.arrayBuffer().then((b) => new Int8Array(b)) : undefined)) : undefined,
    ]);
    const colours = strandColours();
    const group = await buildGroom(style.strands, buffer, colours, {
      scalp: false,
      fine: category === "eyebrows" || category === "eyelashes",
      soft: category === "eyelashes",
      lidFix,
      shapeFollow: category === "eyebrows", // hairs lying on the skin keep to it when the face's shape bends it
    });
    group.name = category;
    group.userData.style = style.id;
    if (style.stubbleMask && style.stubble) underStubble(group, style.stubbleMask, style.stubble, colours.uniforms.uHairShadow.value);
    return group;
  }
  // Otherwise glasses: a .glb, with its look in index.json (pipeline glasses_gen.py)
  const [loader, buffer] = await Promise.all([gltfLoader(), download]);
  const gltf = await loader.parseAsync(buffer, MODELS_BASE);
  const node = gltf.scene.getObjectByName(category);
  if (!node) throw new Error(`no "${category}" node in ${style.file}`);
  try {
    dressGlasses(node, style.glasses!);
  } catch (err) {
    disposePiece(node);
    throw err;
  }
  for (const mesh of meshesOf(node)) mesh.frustumCulled = false; // morphs move vertices; the face is always in view anyway
  node.userData.style = style.id;
  return node;
}

function remove(node: Object3D): void {
  (node.userData.unfit as (() => void) | undefined)?.();
  node.parent?.remove(node);
  for (const m of meshesOf(node)) if (!m.userData.groom) morphs.unbind(m);
  disposePiece(node);
}

/**
 * Take a category's piece off the head for `next` (null = none): at once, or with `crossfade` (Random character, Reset)
 * at the end of lib/pieceFade.ts's batch.
 */
function detach(category: AddonCategory, crossfade = false, next: Object3D | null = null): void {
  const node = addonRig.meshes[category];
  addonRig.meshes[category] = null;
  if (crossfade && swapPiece(node, next, () => node && remove(node))) return;
  if (node) remove(node);
}

/** The old style stays on the head until the new one is ready; then swapped at once, or cross-faded (see detach). */
/** Resolves when the piece is ready to be seen: glasses once their first fit to this face is on. */
function attach(category: AddonCategory, node: Object3D, parent: Object3D, crossfade = false): Promise<void> | undefined {
  detach(category, crossfade, node);
  parent.add(node);
  addonRig.meshes[category] = node;
  for (const m of meshesOf(node)) if (!m.userData.groom) morphs.bind(m); // strand pieces follow the skin themselves
  applyAddons(0, category);
  if (category !== "glasses") return;
  const { fitted, unfit } = fitGlasses(node, parent); // on this face, not only the baked one
  node.userData.unfit = unfit;
  return fitted;
}

// Per category: only the latest request attaches, and the superseded fetch is aborted.
const requests = perCategory(() => 0);
const inflight = perCategory(() => null as AbortController | null);

/** Attach (or fetch, then attach) the style chosen for a category. No-op until the head is mounted. `crossfade`: see detach(). */
export async function syncAddon(category: AddonCategory, crossfade = false): Promise<void> {
  const id = ++requests[category];
  inflight[category]?.abort();
  inflight[category] = null;
  const chosen = addonState[category];
  const style = chosen === "none" ? undefined : addonStyleById(category, chosen);
  if (!style || !addonRig.parent || addonRig.meshes[category]?.userData.style === style.id) {
    if (!style || !addonRig.parent) detach(category, crossfade && !!addonRig.parent);
    addonRig.loading[category] = false;
    if (addonRig.parent) partDone(category); // none, or already on a mounted head: nothing to wait for
    notify();
    return;
  }
  addonRig.loading[category] = true;
  notify();
  const controller = (inflight[category] = new AbortController());
  try {
    const node = await loadAddon(category, style, controller.signal);
    if (id !== requests[category] || !addonRig.parent) {
      disposePiece(node); // superseded (or the head went away) while parsing
      return;
    }
    await attach(category, node, addonRig.parent, crossfade);
  } catch (err) {
    if (!controller.signal.aborted) {
      console.error("addons: failed to load", style.file, err);
      // Show what is really on the head: the picker goes back to the attached style (or None). Stored too, so a reload
      // doesn't ask for the failed file again.
      if (id === requests[category]) {
        addonState[category] = (addonRig.meshes[category]?.userData.style as AddonStyle | undefined) ?? "none";
        persist();
      }
    }
  } finally {
    if (id === requests[category]) {
      inflight[category] = null;
      addonRig.loading[category] = false;
      partDone(category); // attached or failed: the loader's reveal stops waiting either way
      notify();
    }
  }
}

/** FaceCanvas, at hydration: start downloading the saved (or default) styles now, so they are on the head at the reveal. */
export function prefetchAddons(): void {
  loadAddonState();
  for (const c of ADDON_CATEGORIES) {
    const chosen = addonState[c];
    const style = chosen === "none" ? undefined : addonStyleById(c, chosen);
    if (style) prefetchPart(c, MODELS_BASE + style.file);
  }
}

let unsubscribeHair: (() => void) | null = null;

/** Head.tsx: the head's root node exists; attach the chosen add-ons under it. */
export function mountAddons(parent: Object3D): void {
  loadAddonState();
  addonRig.parent = parent;
  unsubscribeHair ??= onHairChange((seconds) => applyAddons(seconds)); // brows, lashes and beard follow the hair colour, blending with it
  for (const c of ADDON_CATEGORIES) void syncAddon(c);
}

/** Head.tsx cleanup: drop everything with the head. */
export function unmountAddons(): void {
  finishPieceFade(); // a fade in progress ends with the head
  unsubscribeHair?.();
  unsubscribeHair = null;
  for (const c of ADDON_CATEGORIES) {
    requests[c]++; // any load in flight is discarded when it lands
    inflight[c]?.abort();
    inflight[c] = null;
    detach(c);
    addonRig.loading[c] = false;
  }
  addonRig.parent = null;
  notify();
}

/**
 * Resolves once the style is on the head (or failed, or was superseded). `crossfade`: join lib/pieceFade.ts's open
 * batch (Random character, Reset); the Style tab swaps at once.
 */
export function setAddonStyle(category: AddonCategory, style: AddonStyle, crossfade = false): Promise<void> {
  addonState[category] = style;
  persist();
  return syncAddon(category, crossfade);
}

/** `seconds` > 0 blends the beard's colour (Random character, with the morph); the Style tab changes it at once. */
export function setFacialHairColour(colour: FacialHairColour, seconds = 0): void {
  addonState.facialHairColour = colour;
  persist();
  applyAddons(seconds, "facialHair");
  notify();
}
