"""The Age slider: a runtime mix of the semantic sliders (shape) plus the web app's skin ageing (wrinkles).

Shape: config/age.toml [shape] and [controls] are slider weights at Age +1. They are expanded here into morph
weights of real head.glb targets (a baked semantic slider is its own target; head size and the fine-tune
controls are mixes themselves), so the web app applies Age as one more mix slider: no extra bytes.

Skin: GNM has no textures, so wrinkles are drawn procedurally in the skin shader from each point's rest (template)
position. The shader needs a few landmarks in template space; they go to web/src/data/ageing.json together with
the [skin] onsets and depths.
"""
from __future__ import annotations

import argparse
import json
import tomllib
from pathlib import Path

import numpy as np

from . import semantic
from .gnm import GNM, OUT_DIR, PIPELINE_DIR, REPO_DIR

AGE_TOML = PIPELINE_DIR / "config" / "age.toml"
AGEING_JSON = REPO_DIR / "web" / "src" / "data" / "ageing.json"
# landmarks the skin shader uses (left side; the shader mirrors with |x|)
SHADER_LANDMARKS = ["trichion", "glabella", "nasion", "brow_inner_l", "endocanthion_l", "exocanthion_l", "lid_lower_l",
                    "alare_l", "subnasale", "labrale_superius", "cheilion_l", "labrale_inferius", "pogonion", "menton"]


def load(path: Path = AGE_TOML) -> dict:
    with open(path, "rb") as f:
        return tomllib.load(f)


def age_combo(sol, controls: list[dict], sigma_scale: float, cfg: dict | None = None) -> dict[str, float]:
    """{real morph target: weight at Age +1}."""
    cfg = cfg or load()
    out: dict[str, float] = {}

    def add(target: str, w: float) -> None:
        out[target] = out.get(target, 0.0) + w

    for sid, w in cfg.get("shape", {}).items():
        if sid not in sol.ids:
            raise KeyError(f"age.toml: {sid!r} is not a semantic slider")
        k = sol.ids.index(sid)
        if sol.baked[k]:
            add(semantic.TARGET_PREFIX + sid, float(w))
        else:
            for t, cw in sol.combo(k, sigma_scale).items():
                add(t, float(w) * cw)
    by_id = {c["id"]: c for c in controls}
    for cid, w in cfg.get("controls", {}).items():
        c = by_id[cid]
        for t, cw in (c.get("combo") or {c["target"]: 1.0}).items():
            add(t, float(w) * cw)
    return {t: round(v, 5) for t, v in out.items() if abs(v) > 1e-5}


def write_ageing_json(gnm: GNM, cfg: dict | None = None) -> dict:
    cfg = cfg or load()
    lm = semantic.config_landmarks(semantic.load_config())
    doc = {
        "note": "Generated by pipeline/src/ftv_pipeline/age.py from config/age.toml and the semantic landmarks (template space, metres).",
        "landmarks": {n: [round(float(v), 5) for v in gnm.template[lm[n]].mean(0)] for n in SHADER_LANDMARKS},
        "skin": cfg["skin"],
    }
    AGEING_JSON.write_text(json.dumps(doc, indent=1) + "\n")
    return doc


def preview_main(argv=None) -> None:
    """Shape only (the skin is drawn by the web app): Age -1 / 0 / +1, front and three-quarter."""
    from PIL import Image, ImageDraw

    from .emotions import solve_controls
    from .export_glb import load_config as load_components

    p = argparse.ArgumentParser(description=preview_main.__doc__)
    p.add_argument("--size", type=int, default=360)
    args = p.parse_args(argv)
    gnm = GNM.load()
    sol = semantic.solve(gnm, semantic.load_config())
    sigma = float(load_components()["export"]["sigma_scale"])
    controls = solve_controls(gnm)
    combo = age_combo(sol, controls, sigma)
    # expand the combo back to vertex deltas: real targets = sem_* (baked), head_* raw identity, expression raw
    delta = np.zeros_like(gnm.template)
    for t, w in combo.items():
        if t.startswith(semantic.TARGET_PREFIX):
            delta += np.float32(w) * sol.delta(gnm, sol.ids.index(t[len(semantic.TARGET_PREFIX):]))
        else:
            delta += np.float32(w * sigma) * gnm.delta(t)
    r = semantic.head_renderer(gnm, args.size)
    sheet = Image.new("RGB", (3 * args.size, 2 * args.size + 30), "#1f1f1f")
    d = ImageDraw.Draw(sheet)
    for c, (w, label) in enumerate([(-1.0, "Age -1 (younger)"), (0.0, "0"), (1.0, "Age +1 (older, shape only)")]):
        d.text((c * args.size + 10, 6), label, fill="white", font=semantic.label_font(16))
        for row, yaw in enumerate((0.0, 35.0)):
            r.set_positions(gnm.template + np.float32(w) * delta)
            r.look(*semantic.FRAMES["face"], yaw)
            tile = OUT_DIR / "age" / "_tile.png"
            r.screenshot(tile)
            sheet.paste(Image.open(tile).convert("RGB"), (c * args.size, 30 + row * args.size))
    (OUT_DIR / "age" / "_tile.png").unlink()
    sheet.save(OUT_DIR / "age" / "preview.png")
    print(f"{len(combo)} targets in the Age mix -> {OUT_DIR / 'age' / 'preview.png'}")
