"""`uv run export-groom <id> [id ...]`: our procedural grooms (groom.py) → web/public/models/hair/<id>.strands.bin, a
thumbnail, and an entry (kind "strands") in hair/index.json. The web app draws them with lib/groom.ts. Everything here
is generated by this project (MIT): no third-party hair data. `entry` and `thumbnail` are shared by every strand tool.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
from PIL import Image

from .gnm import GNM, OUT_DIR
from .groom import CONFIG as GROOMS_CONFIG
from .groom import Groom, build, encode, load_specs, render_views
from .hair_index import HAIR_MODELS_DIR, INDEX, THUMB_SIZE, THUMBS_DIR

WORK = OUT_DIR / "groom"


def mix_hex(a: str, b: str, t: float) -> str:
    ca, cb = (np.array([int(h[k: k + 2], 16) for k in (1, 3, 5)]) for h in (a, b))
    return "#" + "".join(f"{round(v):02x}" for v in ca * (1 - t) + cb * t)


def thumbnail(groom: Groom, gnm: GNM) -> Path:
    sheet = render_views(groom, WORK / f"{groom.spec.id}-thumb.png", size=4 * THUMB_SIZE, views=(35,), gnm=gnm)
    im = Image.open(sheet).convert("RGB")
    w, h = im.size
    crop = im.crop((int(w * 0.18), int(h * 0.02), int(w * 0.82), int(h * 0.66)))  # the head, not the bust
    crop = crop.resize((THUMB_SIZE, THUMB_SIZE), Image.LANCZOS)
    path = THUMBS_DIR / f"{groom.spec.id}.webp"
    crop.save(path, "WEBP", lossless=True)
    return path


def entry(groom: Groom, nbytes: int, *, mesh_fields: bool = False) -> dict:
    """A style's index entry. `mesh_fields`: also the vertex/triangle/target counts, lum, normalMap and alphaCutoff,
    which the add-on indexes (brows, lashes, beards) still carry; the hair index doesn't."""
    s = groom.spec
    N, P, _ = groom.strands.shape
    counts = {"vertices": int(N * P), "triangles": int(N * (P - 1) * 2)} if mesh_fields else {}
    return {
        "id": s.id,
        "label": s.label,
        "kind": "strands",
        "file": f"hair/{s.id}.strands.bin",
        "thumb": f"hair/thumbs/{s.id}.webp",
        **counts,
        "bytes": int(nbytes),
        **({"targets": 0} if mesh_fields else {}),  # roots follow the skin at runtime (lib/groom.ts), no morph targets
        "natural": mix_hex(s.natural[0], s.natural[1], 0.45),  # the Natural chip
        **({"lum": {"median": 0.05, "p98": 0.2}, "normalMap": False, "alphaCutoff": 0} if mesh_fields else {}),
        "author": "Face to Voice (procedural groom)",
        "pack": "groom",
        "strands": {
            "count": int(N),
            "points": int(P),
            "children": list(s.children),
            "childRadiusMm": s.child_radius_mm,
            "widthMm": s.width_mm,
            "tipWidth": s.tip_width,
            "coverMin": s.cover_min,
            "shine": s.shine,
            "root": s.natural[0],
            "tip": s.natural[1],
        },
    }


def merge_index(entries: list[dict]) -> tuple[int, int]:
    """A re-exported groom refreshes what this file generates (file, counts, strands …) in place; everything else in its
    entry is curated (the label, and haircs_review's picker fields: group, type, curly, fringe) and stays, as does its
    place in the picker. A new groom is listed first. Returns (refreshed, new)."""
    index = json.loads(INDEX.read_text())
    listed = {e["id"]: e for e in index["styles"]}
    new = []
    for e in entries:
        old = listed.get(e["id"])
        if old is None:
            new.append(e)
            continue
        label = old.get("label", e["label"])
        old.update(e)  # same dict in the list: its position and key order stay
        old["label"] = label
    index["styles"] = new + index["styles"]
    INDEX.write_text(json.dumps(index, indent=2, ensure_ascii=False) + "\n")
    return len(entries) - len(new), len(new)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("ids", nargs="+", help=f"styles from {GROOMS_CONFIG.name} (each one is shipped in the picker)")
    args = ap.parse_args()
    specs = load_specs()
    unknown = [sid for sid in args.ids if sid not in specs]
    if unknown:
        raise SystemExit(f"unknown groom(s) {', '.join(unknown)}; {GROOMS_CONFIG.name} has: {', '.join(specs)}")
    gnm = GNM.load()
    WORK.mkdir(parents=True, exist_ok=True)
    THUMBS_DIR.mkdir(parents=True, exist_ok=True)
    entries = []
    for sid in args.ids:
        g = build(specs[sid], gnm)
        data = encode(g)
        (HAIR_MODELS_DIR / f"{sid}.strands.bin").write_bytes(data)
        thumbnail(g, gnm)
        entries.append(entry(g, len(data)))
        print(f"    → web/public/models/hair/{sid}.strands.bin {len(data) / 1000:.0f} KB")
    refreshed, new = merge_index(entries)
    print(f"index: {refreshed} groom(s) refreshed in place (curated fields kept), {new} new listed first in {INDEX.name}")
