"""`uv run glasses-gen [id …]`: our own glasses (MIT), built from numbers in config/glasses.toml.

Every part is a smooth sweep: a rounded cross-section carried along a path (the rim round a lens outline, the bridge,
the temple arms, the brow bar), so nothing is faceted. Lens outlines are superellipses with a separate squareness per
quadrant plus a few warps (cat-eye lift, wayfarer taper, aviator teardrop) or rounded polygons (hexagon, octagon).
The front gets face form (curving back at its ends) and pantoscopic tilt, the lenses a base curve.

Fitting uses the optician's solver (glasses_fit.place_glasses: seat on the nose, splay the arms past the temples, tilt
them onto the ears) and its binder (identity targets, arms follow the head's width).

What ships (web/public/models/addons/glasses/<id>.glb, the add-on contract of web/src/lib/data.ts): node and mesh "glasses"; primitive
"glasses" (the frame: one colour map + a metallic-roughness map, a 256×128 atlas: acetate pattern on the left half,
flat cells for metal, nose pads, temple tips and the nylon cord on the right) and primitive "glasses_lens" (front wall
of each lens, plus the edge of rimless lenses). index.json carries each style's lens look ("glasses" field).
"""
from __future__ import annotations

import argparse
import io
import json
import struct
import time
import tomllib
from dataclasses import dataclass, field
from pathlib import Path
from types import SimpleNamespace

import numpy as np
from PIL import Image
from scipy.spatial import Delaunay

from .addon_fit import ADDONS_MODELS_DIR, ADDONS_OUT
from .export_glb import GLTFPACK_FLAGS, vertex_normals
from .glasses_fit import GlassesFit, place_glasses
from .glb import GlbWriter, srgb_to_linear
from .gnm import PIPELINE_DIR
from .head_context import head_context
from .landmarks import gnm_landmarks, landmark_table
from .tools import gltfpack

CONFIG = PIPELINE_DIR / "config" / "glasses.toml"
OUT = ADDONS_OUT / "glasses-gen"
MODELS = ADDONS_MODELS_DIR / "glasses"
LICENCE = "MIT — generated by the face-to-voice pipeline (glasses_gen.py); no third-party assets"
GLASSES_GLTFPACK_FLAGS = (*GLTFPACK_FLAGS, "-vtf")  # -vtf: float UVs, so gltfpack adds no KHR_texture_transform

# texture atlas: 256 × 128; the acetate pattern fills u 0…0.5, the flat cells sit on the right half (4 × 2 cells)
CELLS = {"metal": 0, "metal2": 1, "pad": 2, "tip": 3, "cord": 4, "hinge": 5}


def cell_uv(name: str) -> tuple[float, float]:
    i = CELLS[name]
    return 0.5 + (i % 4 + 0.5) / 8.0, (i // 4 + 0.5) / 2.0


# --- lens outlines (mm, lens-local: u away from the nose, v up, centred on the lens box) ----------------------------


def superellipse(a_out, a_in, b_top, b_bot, n, N=720) -> np.ndarray:
    """n = squareness per quadrant (outer-top, inner-top, inner-bottom, outer-bottom); 2 = ellipse, large = box."""
    t = np.linspace(0, 2 * np.pi, N, endpoint=False)
    c, s = np.cos(t), np.sin(t)
    q = np.where(s >= 0, np.where(c >= 0, 0, 1), np.where(c < 0, 2, 3))
    nn = np.asarray(n, float)[q]
    u = np.where(c >= 0, a_out, a_in) * np.sign(c) * np.abs(c) ** (2 / nn)
    v = np.where(s >= 0, b_top, b_bot) * np.sign(s) * np.abs(s) ** (2 / nn)
    return np.stack([u, v], 1)


def rounded_polygon(sides: int, a: float, b: float, rot: float, iterations: int = 4) -> np.ndarray:
    t = np.arange(sides) / sides * 2 * np.pi + rot
    p = np.stack([np.cos(t), np.sin(t)], 1)
    for _ in range(iterations):  # Chaikin: corner cutting → rounded corners
        q = np.roll(p, -1, 0)
        p = np.stack([0.8 * p + 0.2 * q, 0.2 * p + 0.8 * q], 1).reshape(-1, 2)
    p /= np.abs(p).max(0)
    return p * (a, b)


def outline(shape: str, W: float, H: float, nasal: float = 0.0) -> np.ndarray:
    """`nasal` (mm): how far the lower nose-side corner is cut away diagonally, as plastic frames are, so the rim
    clears the side of the nose where it widens (without it the frame rests on that corner, ~1 cm off the face)."""
    a, b = W / 2, H / 2
    if shape == "round":
        p = superellipse(a, a, b, b, (2, 2, 2, 2))
    elif shape == "oval":
        p = superellipse(a, a, b, b, (2.3, 2.3, 2.3, 2.3))
    elif shape == "rect":
        p = superellipse(a, a, b, b, (4.2, 4.2, 4.2, 4.2))
    elif shape == "square":
        p = superellipse(a, a, b, b, (4.5, 4.5, 4.5, 4.5))
    elif shape == "panto":  # round below, a flatter brow line on top
        p = superellipse(a, a, b, b, (3.4, 3.4, 2.1, 2.1))
    elif shape == "browline":
        p = superellipse(a, a, b, b, (4.0, 3.4, 2.4, 2.6))
    elif shape == "dframe":  # flat top, round bottom, a squarer outer side
        p = superellipse(a, a, b, b, (5.0, 3.2, 2.2, 2.8))
    elif shape == "wayfarer":  # trapezoid: the top wider than the bottom, the outer top corner raised
        p = superellipse(a, a, b, b, (4.6, 3.6, 2.6, 3.0))
        p[:, 0] *= 1 + 0.12 * p[:, 1] / b
        p[:, 1] += 2.0 * np.clip(p[:, 0] / a, 0, None) ** 3 * np.clip(p[:, 1] / b, 0, None)
    elif shape == "cateye":  # outer top corner swept up and out
        p = superellipse(a, a * 0.95, b, b * 0.9, (5.0, 3.0, 2.2, 2.0))
        lift = np.clip(p[:, 0] / a, 0, None) ** 4 * np.clip(p[:, 1] / b + 0.2, 0, None)
        p[:, 1] += 9.0 * lift
        p[:, 0] += 4.0 * lift
        p[:, 0] -= 0.12 * a * np.clip(p[:, 0] / a, 0, None) * np.clip(-p[:, 1] / b, 0, None)  # outer bottom tucked in
        p[:, 1] -= 0.25 * np.clip(-p[:, 0] / a, 0, None) * b * np.clip(p[:, 1] / b, 0, None)  # the inner top slopes down
    elif shape == "aviator":  # teardrop: straight-ish top, deep outer bottom, inner side slanting
        p = superellipse(a, a * 0.92, b * 0.78, b * 1.0, (3.0, 3.6, 1.7, 2.1))
        low = np.clip(-p[:, 1] / b, 0, None)
        p[:, 0] += 5.0 * low ** 1.5
        p[:, 1] += 0.08 * b * np.clip(-p[:, 0] / a, 0, None)
    elif shape == "hexagon":
        p = rounded_polygon(6, a, b, 0.0)
    elif shape == "octagon":
        p = rounded_polygon(8, a, b, np.pi / 8)
    else:
        raise ValueError(f"unknown lens shape {shape!r}")
    p -= (p.max(0) + p.min(0)) / 2  # centred on its box
    if nasal:
        a_in = -p[:, 0].min()
        low = np.clip((-p[:, 1] - 0.05 * b) / (0.95 * b), 0, 1) ** 1.3  # 0 at mid-height … 1 at the bottom
        p[:, 0] += nasal * low * np.clip(-p[:, 0] / a_in, 0, 1) ** 2  # only the nose side moves, outwards
    return resample_closed(p, 120)


def resample_closed(p: np.ndarray, n: int) -> np.ndarray:
    """n points evenly spaced along a closed polyline, counter-clockwise, starting at the outer middle."""
    if np.sum(p[:, 0] * np.roll(p[:, 1], -1) - np.roll(p[:, 0], -1) * p[:, 1]) < 0:
        p = p[::-1]
    q = np.vstack([p, p[:1]])
    seg = np.linalg.norm(np.diff(q, axis=0), axis=1)
    s = np.concatenate([[0], np.cumsum(seg)])
    t = np.linspace(0, s[-1], n, endpoint=False)
    out = np.stack([np.interp(t, s, q[:, 0]), np.interp(t, s, q[:, 1])], 1)
    start = np.argmin(np.abs(np.arctan2(out[:, 1], out[:, 0])))
    return np.roll(out, -start, 0)


def outward_normals(p: np.ndarray) -> np.ndarray:
    """Unit outward normals of a counter-clockwise closed polyline (smoothed over neighbours)."""
    t = np.roll(p, -1, 0) - np.roll(p, 1, 0)
    n = np.stack([t[:, 1], -t[:, 0]], 1)
    return n / np.linalg.norm(n, axis=1, keepdims=True)


# --- sweeps ---------------------------------------------------------------------------------------------------------


def rrect(s0: float, s1: float, z0: float, z1: float, r: float, k: int = 3) -> np.ndarray:
    """Closed rounded rectangle in (s, z), counter-clockwise, 4·(k+1) points."""
    r = min(r, (s1 - s0) / 2 - 1e-4, (z1 - z0) / 2 - 1e-4)
    pts = []
    for (cs, cz), a0 in (((s1 - r, z1 - r), 0.0), ((s0 + r, z1 - r), 0.5 * np.pi), ((s0 + r, z0 + r), np.pi), ((s1 - r, z0 + r), 1.5 * np.pi)):
        for j in range(k + 1):
            a = a0 + 0.5 * np.pi * j / k
            pts.append((cs + r * np.cos(a), cz + r * np.sin(a)))
    return np.array(pts)


def circle(r: float, k: int = 10) -> np.ndarray:
    a = np.linspace(0, 2 * np.pi, k, endpoint=False)
    return np.stack([r * np.cos(a), r * np.sin(a)], 1)


@dataclass
class Part:
    """A piece of mesh: positions (mm, frame space), triangles, UVs, and whether it is lens."""

    positions: np.ndarray
    triangles: np.ndarray
    uvs: np.ndarray
    lens: bool = False
    front: bool = True  # gets the front's face form and tilt (temples are placed after it)


def sweep(centres: np.ndarray, A: np.ndarray, B: np.ndarray, profiles: np.ndarray, closed: bool, uv) -> Part:
    """Rings of `profiles` (M, K, 2: offsets along A and B) round each path point; quads between rings, a dome-free
    open end is closed with a fan. `uv`: (M, K, 2) array or a fixed (u, v)."""
    M, K, _ = profiles.shape
    pos = centres[:, None, :] + profiles[..., :1] * A[:, None, :] + profiles[..., 1:] * B[:, None, :]
    tris = []
    rings = M if closed else M - 1
    for i in range(rings):
        i2 = (i + 1) % M
        for k in range(K):
            k2 = (k + 1) % K
            a, b, c, d = i * K + k, i2 * K + k, i2 * K + k2, i * K + k2
            tris += [(a, b, c), (a, c, d)]
    pos = pos.reshape(-1, 3)
    tris = np.array(tris)
    uvs = np.broadcast_to(np.asarray(uv, float), (M, K, 2)).reshape(-1, 2).copy() if np.ndim(uv) == 1 else uv.reshape(-1, 2)
    if not closed:  # caps
        for ring, flip in ((0, True), (M - 1, False)):
            c = len(pos)
            pos = np.vstack([pos, centres[ring]])
            uvs = np.vstack([uvs, uvs[ring * K]])
            fan = [(c, ring * K + (k + 1) % K, ring * K + k) if flip else (c, ring * K + k, ring * K + (k + 1) % K) for k in range(K)]
            tris = np.vstack([tris, fan])
    # outward winding: the first quad's normal must point away from its ring's centre
    p = pos[tris[:4]]
    nrm = np.cross(p[:, 1] - p[:, 0], p[:, 2] - p[:, 0]).sum(0)
    if np.dot(nrm, pos[tris[0, 0]] - centres[0]) < 0:
        tris = tris[:, ::-1]
    return Part(pos, tris, uvs)


def path_frames(path: np.ndarray, up=(0.0, 1.0, 0.0)) -> tuple[np.ndarray, np.ndarray]:
    """Per path point: A = sideways (horizontal, across the path), B = up-ish (perpendicular to the path and A)."""
    T = np.gradient(path, axis=0)
    T /= np.linalg.norm(T, axis=1, keepdims=True)
    A = np.cross(T, np.asarray(up))
    A /= np.linalg.norm(A, axis=1, keepdims=True)
    B = np.cross(A, T)
    return A, B


# --- the frame ------------------------------------------------------------------------------------------------------


@dataclass
class Style:
    id: str
    label: str
    shape: str
    kind: str
    W: float
    H: float
    bridge: float
    rim: float
    rim_top: float
    depth: float
    wire: float
    drop: float
    wrap: float
    tilt: float
    base: float
    temple_height: float
    temple_thick: float
    nasal: float = 0.0
    frame: dict = field(default_factory=dict)
    metal: dict = field(default_factory=dict)
    lens: dict = field(default_factory=dict)
    double_bridge: bool = False


def load_styles() -> dict[str, Style]:
    cfg = tomllib.loads(CONFIG.read_text())
    d = cfg["defaults"]
    out = {}
    for sid, s in cfg["style"].items():
        g = {**d, **s}
        out[sid] = Style(id=sid, label=g["label"], shape=g["shape"], kind=g["kind"], W=g["size"][0], H=g["size"][1], bridge=g["bridge"],
                         rim=g["rim"], rim_top=g["rim_top"], depth=g["depth"], wire=g["wire"], drop=g["drop"], wrap=g["wrap"], tilt=g["tilt"],
                         base=g["base"], temple_height=g["temple_height"], temple_thick=g["temple_thick"], nasal=g["nasal"] * g["size"][1], frame=g.get("frame", {}),
                         metal=g.get("metal", {}), lens=g.get("lens", {}), double_bridge=g.get("double_bridge", False))
    return out


def acetate_uv(pos: np.ndarray) -> np.ndarray:
    """Planar map of the front onto the pattern half of the atlas."""
    return np.stack([np.clip((pos[:, 0] + 80) / 160, 0.01, 0.99) * 0.5, np.clip((pos[:, 1] + 40) / 80, 0.01, 0.99)], 1)


def lens_sheet(ol: np.ndarray, centre: np.ndarray, base: float, spacing: float = 4.0) -> Part:
    """The lens: a single curved sheet filling the outline (Delaunay over the outline + an inner grid)."""
    from matplotlib.path import Path as MPath

    poly = MPath(ol)
    lo, hi = ol.min(0), ol.max(0)
    gx, gy = np.meshgrid(np.arange(lo[0], hi[0], spacing), np.arange(lo[1], hi[1], spacing))
    grid = np.stack([gx.ravel(), gy.ravel()], 1)
    inner = grid[poly.contains_points(grid, radius=-spacing * 0.6)]
    pts = np.vstack([ol, inner])
    tri = Delaunay(pts).simplices
    keep = poly.contains_points(pts[tri].mean(1))
    tri = tri[keep]
    # The front curve, pinned at the edge: the whole edge stays in the rim's groove (a plain sphere would pull the edge
    # of a wide lens back out of the frame) and the middle bulges forward by the sphere's sag.
    d = pts - centre
    edge = ol - centre
    ang_e = np.arctan2(edge[:, 1], edge[:, 0])
    order = np.argsort(ang_e)
    ang_e, rad_e = ang_e[order], np.linalg.norm(edge, axis=1)[order]
    R = np.interp(np.arctan2(d[:, 1], d[:, 0]), np.concatenate([ang_e - 2 * np.pi, ang_e, ang_e + 2 * np.pi]), np.tile(rad_e, 3))
    bulge = (rad_e.mean() ** 2) / (2 * base)
    z = bulge * np.clip(1 - (np.linalg.norm(d, axis=1) / np.maximum(R, 1e-6)) ** 2, 0, 1)
    pos = np.column_stack([pts, z])
    uv = np.stack([(pts[:, 0] - lo[0]) / (hi[0] - lo[0]), (hi[1] - pts[:, 1]) / (hi[1] - lo[1])], 1)  # v = 0 at the top
    return Part(pos, tri, uv, lens=True)


def build_frame(st: Style) -> tuple[list[Part], dict]:
    """All parts in frame space (mm): x across (+x = the head's +x side), y up, z forward; the lens boxes centred at
    y = 0 (the pupils sit st.drop above), the front face at z = 0."""
    parts: list[Part] = []
    ol = outline(st.shape, st.W, st.H, nasal=st.nasal if st.kind in ("acetate", "browline") else 0.0)
    a_in = -ol[:, 0].min()
    cx = st.bridge / 2 + a_in  # lens box centre x (+x side)
    acetate = st.kind in ("acetate",)
    hinge = {}
    for side in (1, -1):
        p2 = ol.copy()
        p2[:, 0] = side * (cx + p2[:, 0])
        if side < 0:
            p2 = p2[::-1]
        n2 = outward_normals(p2)
        centre2 = np.array([side * cx, 0.0])
        v_rel = (p2[:, 1] - p2[:, 1].min()) / np.ptp(p2[:, 1])  # 0 at the bottom, 1 at the top
        out_rel = np.clip((side * p2[:, 0] - cx) / (st.W / 2), -1, 1)  # −1 at the nose, +1 at the hinge
        P3 = np.column_stack([p2, np.zeros(len(p2))])
        N3 = np.column_stack([n2, np.zeros(len(p2))])
        Z3 = np.tile([0.0, 0.0, 1.0], (len(p2), 1))
        lens_depth = -st.depth * 0.5 if acetate or st.kind == "browline" else 0.0
        if acetate:
            wing = 3.0 if st.shape == "cateye" else 1.2
            w = st.rim + st.rim_top * np.clip((v_rel - 0.55) / 0.35, 0, 1) ** 1.5 + wing * np.clip(out_rel, 0, 1) ** 4 * np.clip(v_rel - 0.3, 0, 1)
            prof = np.stack([rrect(-0.6, wi, -st.depth, 0.0, 1.4) for wi in w])
            parts.append(sweep(P3, N3, Z3, prof, True, (0.25, 0.5)))
            parts[-1].uvs = acetate_uv(parts[-1].positions)
        elif st.kind in ("metal", "browline"):
            prof = np.tile(circle(st.wire, 8), (len(p2), 1, 1))
            parts.append(sweep(P3 + N3 * st.wire * 0.6 + (0, 0, lens_depth), N3, Z3, prof, True, cell_uv("metal")))
            if st.kind == "browline":  # the plastic brow over the top
                top = v_rel > 0.42
                idx = np.where(top)[0]
                # the top run of the outline as one open path, in order
                start = idx[np.argmax(np.diff(np.concatenate([[idx[-1] - len(p2)], idx])) > 1)] if not top.all() else 0
                order = [(start + j) % len(p2) for j in range(len(p2)) if top[(start + j) % len(p2)]]
                order = np.array(order)
                wt = st.rim * np.clip((v_rel[order] - 0.42) / 0.3, 0.15, 1) ** 0.7 + 1.0 * np.clip(out_rel[order], 0, 1) ** 3
                prof = np.stack([rrect(-1.0, wi, -st.depth, 0.0, 1.4) for wi in wt])
                part = sweep(P3[order], N3[order], Z3[order], prof, False, (0.25, 0.5))
                part.uvs = acetate_uv(part.positions)
                parts.append(part)
        elif st.kind == "halfrim":
            top = v_rel > 0.5
            idx = np.where(top)[0]
            start = idx[np.argmax(np.diff(np.concatenate([[idx[-1] - len(p2)], idx])) > 1)]
            order = np.array([(start + j) % len(p2) for j in range(len(p2)) if top[(start + j) % len(p2)]])
            prof = np.stack([rrect(-0.6, 2.4, -2.6, 0.0, 0.9) for _ in order])
            parts.append(sweep(P3[order], N3[order], Z3[order], prof, False, cell_uv("metal")))
            low = ~top
            idx = np.where(low)[0]
            start = idx[np.argmax(np.diff(np.concatenate([[idx[-1] - len(p2)], idx])) > 1)]
            order = np.array([(start + j) % len(p2) for j in range(len(p2)) if low[(start + j) % len(p2)]])
            prof = np.tile(circle(0.32, 6), (len(order), 1, 1))
            parts.append(sweep(P3[order] + (0, 0, -1.2), N3[order], Z3[order], prof, False, cell_uv("cord")))
            lens_depth = -1.2
        # lens, a little inside the rim's groove (rimless: the outline itself, with a visible edge)
        inset = -0.3 if st.kind == "rimless" else 0.3
        lens_ol = p2 + n2 * inset
        lens = lens_sheet(lens_ol, centre2, st.base)
        lens.positions[:, 2] += lens_depth
        parts.append(lens)
        if st.kind == "rimless":  # the lens edge (2 mm thick) catches the light: that is what you see of a rimless lens
            prof = np.tile(np.array([[0.0, 0.0], [0.0, -2.0]]), (len(lens_ol), 1, 1))
            edge = sweep(np.column_stack([lens_ol, lens.positions[: len(lens_ol), 2]]), N3, Z3, prof, True, (0.5, 0.5))
            edge.lens = True
            parts.append(edge)
        # hinge point: the outer edge of the rim, in the upper part of the lens
        k = int(np.argmin(np.abs(p2[:, 1] - 0.3 * st.H / 2) + 100 * (side * p2[:, 0] < cx)))
        reach = (st.rim + 0.8) if acetate else st.wire + 0.6
        hinge[side] = np.array([p2[k, 0] + side * reach * 0.6, p2[k, 1], -st.depth if acetate else lens_depth - 0.8])
        if st.kind in ("metal", "browline", "rimless", "halfrim"):  # end piece: a short bar from the rim back to the hinge
            a = np.array([p2[k, 0] - side * 0.5, p2[k, 1], lens_depth])
            path = np.linspace(a, hinge[side] + (side * 1.0, 0, -2.0), 8)
            A, B = path_frames(path)
            prof = np.tile(rrect(-1.1, 1.1, -1.4, 1.4, 0.6), (len(path), 1, 1))
            parts.append(sweep(path, A, B, prof, False, cell_uv("hinge")))
        if st.kind in ("metal", "browline", "rimless", "halfrim"):  # nose pad on a little arm
            kk = int(np.argmin(np.abs(p2[:, 1] - 0.05 * st.H) + 100 * (side * p2[:, 0] > cx)))
            root = np.array([p2[kk, 0], p2[kk, 1], lens_depth])
            pad = np.array([side * (st.bridge / 2 - 1.5), -0.05 * st.H / 2 - 1.0, lens_depth - 5.0])
            arm = np.array([root, root * 0.5 + pad * 0.5 + (side * 1.0, 1.5, 1.0), pad])
            from scipy.interpolate import make_interp_spline

            arm = make_interp_spline(np.arange(3), arm, k=2)(np.linspace(0, 2, 10))
            A, B = path_frames(arm)
            parts.append(sweep(arm, A, B, np.tile(circle(0.45, 6), (len(arm), 1, 1)), False, cell_uv("metal")))
            # the pad: a flattened ellipsoid facing the nose
            u, v = np.meshgrid(np.linspace(0, 2 * np.pi, 14, endpoint=False), np.linspace(-np.pi / 2, np.pi / 2, 9))
            e = np.stack([0.9 * np.cos(v) * np.cos(u), 4.8 * np.sin(v), 3.0 * np.cos(v) * np.sin(u)], -1).reshape(-1, 3)
            rot = np.radians(side * -25)
            x, z = e[:, 0] * np.cos(rot) - e[:, 2] * np.sin(rot), e[:, 0] * np.sin(rot) + e[:, 2] * np.cos(rot)
            e = np.column_stack([x, e[:, 1], z]) + pad
            ring = 14
            tris = []
            for i in range(8):
                for j in range(ring):
                    a, b, c, d = i * ring + j, (i + 1) * ring + j, (i + 1) * ring + (j + 1) % ring, i * ring + (j + 1) % ring
                    tris += [(a, c, b), (a, d, c)]
            parts.append(Part(e, np.array(tris), np.tile(cell_uv("pad"), (len(e), 1))))
    # bridge
    if acetate:
        # A solid bar between the two rims' inner (nose-side) edges, its top just under where the rims' top is on the
        # nose side, so it joins them like one moulded front instead of sticking out.
        hb = st.rim * 1.1
        # where it meets the rim: the straight-ish nose-side edge of the lens (not the rounded top corner, and on a
        # cat-eye not the higher middle of a top edge that slopes down to the nose), its top kept under that edge's top
        inner = ol[:, 0] < -0.9 * a_in
        top_j = ol[inner, 1].max()
        yc = top_j - hb / 2 - 1.2
        k = np.where(inner)[0][np.argmin(np.abs(ol[inner, 1] - yc))]
        n_k = outward_normals(ol)[k]
        x_edge = cx + ol[k, 0] + n_k[0] * st.rim  # the rim band's outer (nose-side) edge at that height (+x lens)
        xa = x_edge + 1.2  # into the rim a little: one solid piece
        xs = np.linspace(-xa, xa, 24)
        yb = yc - 0.6 * (1 - (xs / xa) ** 2)  # a slight keyhole dip
        path = np.column_stack([xs, yb, np.full_like(xs, -st.depth / 2)])
        A = np.tile([0.0, 1.0, 0.0], (len(xs), 1))
        B = np.tile([0.0, 0.0, 1.0], (len(xs), 1))
        prof = np.stack([rrect(-hb / 2, hb / 2, -st.depth / 2, st.depth / 2, 1.3) for _ in xs])
        part = sweep(path, A, B, prof, False, (0.25, 0.5))
        part.uvs = acetate_uv(part.positions)
        parts.append(part)
    else:
        xa = st.bridge / 2 + 0.8
        xs = np.linspace(-xa, xa, 20)
        top = (ol[:, 1].max() if st.kind != "rimless" else 0.25 * st.H)
        yb = 0.35 * top + 2.5 * (1 - (xs / xa) ** 2)
        zb = (-st.depth * 0.5 if st.kind == "browline" else 0.0) - 1.0 * (1 - (xs / xa) ** 2)
        path = np.column_stack([xs, yb, zb])
        A, B = path_frames(path)
        parts.append(sweep(path, A, B, np.tile(circle(st.wire * 1.05, 8), (len(xs), 1, 1)), False, cell_uv("metal")))
        if st.double_bridge:  # aviator brow bar
            xb = st.bridge / 2 + 6.0
            xs = np.linspace(-xb, xb, 24)
            yt = ol[:, 1].max() - 2.0 + 0.6 * (1 - (xs / xb) ** 2)
            path = np.column_stack([xs, yt, np.full_like(xs, -0.4)])
            A, B = path_frames(path)
            parts.append(sweep(path, A, B, np.tile(circle(st.wire * 0.95, 8), (len(xs), 1, 1)), False, cell_uv("metal")))
    return parts, hinge


def front_transform(p: np.ndarray, st: Style) -> np.ndarray:
    """Face form (the ends curve back) and pantoscopic tilt (the lower rim nearer the cheeks)."""
    q = p.copy()
    half = st.bridge / 2 + st.W
    q[:, 2] -= st.wrap * (q[:, 0] / half) ** 2
    q[:, 2] += np.tan(np.radians(st.tilt)) * q[:, 1]
    return q


def temple(st: Style, side: int, hinge_g: np.ndarray, ear: np.ndarray) -> list[Part]:
    """One temple arm (GNM metres in, metres out): from the hinge straight back over the ear root, then down behind
    the ear. Acetate: one tapering rounded bar; wire frames: a thin rod plus a plastic tip on the earpiece."""
    mm = 0.001
    E = np.array([side * (abs(ear[0]) + 0.0025), ear[1] + 0.0015, ear[2] + 0.002])
    n1 = 40
    straight = np.linspace(hinge_g, E, n1)
    d = (E - hinge_g) / np.linalg.norm(E - hinge_g)
    pts = [E]
    for j in range(1, 16):  # bend down behind the ear, then straight
        ang = np.radians(min(j * 4.0, 34.0))
        dirj = np.array([d[0] * np.cos(ang) - side * 0.12 * np.sin(ang), -np.sin(ang), d[2] * np.cos(ang)])
        dirj /= np.linalg.norm(dirj)
        pts.append(pts[-1] + dirj * 0.0022)
    ear_path = np.array(pts)
    path = np.vstack([straight[:-1], ear_path]) / mm  # mm
    A, B = path_frames(path)
    L = np.concatenate([[0], np.cumsum(np.linalg.norm(np.diff(path, axis=0), axis=1))])
    tip = np.clip((L[-1] - L) / 4.0, 0, 1) ** 0.5  # rounded end
    parts = []
    if st.kind == "acetate":
        hgt = st.temple_height + (st.rim * 1.6 - st.temple_height) * np.clip(1 - L / 14.0, 0, 1) ** 2  # end piece taper
        th = st.temple_thick * np.ones_like(L)
        prof = np.stack([rrect(-t / 2 * s_, t / 2 * s_, -h / 2 * s_, h / 2 * s_, min(1.2, t / 2.2) * max(s_, 0.3)) for t, h, s_ in zip(th, hgt, np.maximum(tip, 0.05))])
        part = sweep(path, A, B, prof, False, (0.25, 0.5))
        u = np.repeat(np.clip(L / L[-1], 0.01, 0.99) * 0.5, prof.shape[1])
        part.uvs = np.vstack([np.column_stack([u, np.tile(np.linspace(0.1, 0.9, prof.shape[1]), len(L))]), part.uvs[len(u):]])
        part.positions *= mm
        part.front = False
        parts.append(part)
    else:
        prof = np.stack([rrect(-0.75, 0.75, -1.0, 1.0, 0.6) * max(s_, 0.4) for s_ in tip])
        part = sweep(path, A, B, prof, False, cell_uv("metal"))
        part.positions *= mm
        part.front = False
        parts.append(part)
        m = L > L[n1 - 2] - 6.0  # noqa: SIM300 (L is an array, not a constant): the plastic tip over the earpiece
        sub = path[m]
        Ls = L[m] - L[m][0]
        s2 = np.clip((Ls[-1] - Ls) / 5.0, 0, 1) ** 0.5 * np.clip(Ls / 3.0, 0, 1) ** 0.5
        prof = np.stack([rrect(-1.3, 1.3, -1.7, 1.7, 1.1) * max(s_, 0.35) for s_ in s2])
        part = sweep(sub, A[m], B[m], prof, False, cell_uv("tip"))
        part.positions *= mm
        part.front = False
        parts.append(part)
    return parts


# --- textures -------------------------------------------------------------------------------------------------------


def pattern(st: Style, size=(128, 128), seed=5) -> np.ndarray:
    """(h, w, 3) sRGB 0..1: the acetate's look (solid, tortoise, havana)."""
    h, w = size
    col = np.array(srgb_hex(st.frame.get("colour", "#111111")))
    kind = st.frame.get("pattern", "solid")
    if kind == "solid":
        return np.broadcast_to(col, (h, w, 3)).copy()
    from scipy import ndimage

    rng = np.random.default_rng(seed)

    def noise(scale):
        g = rng.standard_normal((h // scale + 2, w // scale + 2))
        return ndimage.zoom(g, scale, order=3)[:h, :w]

    n = noise(16) + 0.5 * noise(6) + 0.25 * noise(3)
    n = (n - n.mean()) / n.std()
    amber = np.array(srgb_hex("#a0662a")) if kind == "tortoise" else np.array(srgb_hex("#7a4c22"))
    dark = np.array(srgb_hex("#1c0d06"))
    mid = col
    t = np.clip((n + 0.6) / 1.5, 0, 1)[..., None]  # more dark than amber
    out = np.where(t < 0.5, amber + (mid - amber) * (t / 0.5), mid + (dark - mid) * ((t - 0.5) / 0.5))
    return np.clip(out, 0, 1)


def srgb_hex(h: str) -> list[float]:
    h = h.lstrip("#")
    return [int(h[i: i + 2], 16) / 255 for i in (0, 2, 4)]


def atlas(st: Style) -> tuple[bytes, bytes, str]:
    """→ (colour PNG, metallic-roughness PNG, the frame's main colour as hex for index.json)."""
    W, H = 256, 128
    colour = np.zeros((H, W, 3))
    mr = np.zeros((H, W, 3))  # glTF: G = roughness, B = metalness
    colour[:, :128] = pattern(st)
    mr[:, :128, 1] = st.frame.get("roughness", 0.2)
    metal = st.metal or {"colour": "#a9adb2", "roughness": 0.25}
    cells = {
        "metal": (metal["colour"], metal["roughness"], 1.0),
        "metal2": (metal["colour"], metal["roughness"], 1.0),
        "pad": ("#d9d5cd", 0.2, 0.0),  # clear silicone reads as a pale, glossy grey
        "tip": (st.frame.get("colour", "#1b1b1d") if st.frame else "#1b1b1d", 0.35, 0.0),
        "cord": ("#c8ccd0", 0.4, 0.0),
        "hinge": (metal["colour"], metal["roughness"], 1.0),
    }
    for name, (hexc, rough, metallic) in cells.items():
        i = CELLS[name]
        x0, y0 = 128 + (i % 4) * 32, (i // 4) * 64
        colour[y0: y0 + 64, x0: x0 + 32] = srgb_hex(hexc)
        mr[y0: y0 + 64, x0: x0 + 32, 1] = rough
        mr[y0: y0 + 64, x0: x0 + 32, 2] = metallic
    def png(a):
        buf = io.BytesIO()
        Image.fromarray((np.clip(a, 0, 1) * 255 + 0.5).astype(np.uint8)).save(buf, "PNG", optimize=True)
        return buf.getvalue()
    main = st.frame.get("colour") if st.kind in ("acetate", "browline") else metal["colour"]
    return png(colour), png(mr), main


# --- build, fit, write ----------------------------------------------------------------------------------------------


def assemble(st: Style, ctx) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """→ positions (GNM metres), triangles, uvs, lens and proxy (bool per triangle), before the optician's fit."""
    marks = gnm_landmarks(ctx.gnm)
    eyes = (marks["eye_left"] + marks["eye_right"]) / 2
    origin = np.array([0.0, eyes[1] - st.drop * 0.001, marks["nose_bridge"][2] + 0.004])
    parts, hinge = build_frame(st)
    for p in parts:
        p.positions = front_transform(p.positions, st) * 0.001 + origin
    ear = (marks["ear_top_left"] + marks["ear_top_right"]) / 2
    for side in (1, -1):
        hg = front_transform(hinge[side][None], st)[0] * 0.001 + origin
        parts += temple(st, side, hg, np.array([side * abs(marks["ear_top_left"][0]), ear[1], ear[2]]))
    pos, tris, uvs, lens, proxy = [], [], [], [], []
    n = 0
    for p in parts:
        pos.append(p.positions)
        tris.append(p.triangles + n)
        uvs.append(p.uvs)
        lens.append(np.full(len(p.triangles), p.lens))
        keep = np.zeros(len(p.triangles), bool)  # what the fitting solver looks at (module docstring of `fit`)
        keep[:: max(1, len(p.triangles) // PROXY_PER_PART)] = True
        proxy.append(keep & (not p.lens))
        n += len(p.positions)
    return np.vstack(pos), np.vstack(tris), np.vstack(uvs), np.concatenate(lens), np.concatenate(proxy)


MIN_DELTA_MM = 1.0  # a face-shape slider is baked when it moves the frame at least this far (each costs ~10 KB)
PROXY_PER_PART = 400  # triangles per part the solver tests for clearance (every vertex still moves with the result)


def fit(st: Style, ctx, positions: np.ndarray, triangles: np.ndarray):
    """The optician's solver and the binder (glasses_fit), on our mesh. place_glasses takes a frame placed relative to
    the aligned MakeHuman head's eyes and moves it by (GNM eyes − MakeHuman eyes): our mesh is built on the GNM eyes, so
    it is handed over moved back by that much. `triangles` is a sparse subset (`assemble`'s proxy): the solver samples the
    edges of the triangles it is given, and a smooth frame needs only a few per part; the pose and the binding it
    finds move every vertex."""
    table = landmark_table()
    eyes_mh = (table["eye_left"][0] + table["eye_right"][0]) / 2
    eyes = (table["eye_left"][1] + table["eye_right"][1]) / 2
    shift = (eyes - eyes_mh) * (1, 1, 0)
    asset = SimpleNamespace(style=SimpleNamespace(fit=GlassesFit(min_delta_mm=MIN_DELTA_MM)),
                            aligned=(positions - shift).astype(np.float32), triangles=triangles)
    return place_glasses(asset, ctx)


def write(st: Style, placement, triangles, uvs, lens_mask) -> tuple[dict, int]:
    bound = placement.bound
    names = list(bound.deltas)
    colour_png, mr_png, main_hex = atlas(st)
    w = GlbWriter(generator="face-to-voice pipeline (glasses_gen.py, MIT)")
    tex = w.texture(w.image(colour_png, name="glasses"), clamp=True)
    mr_tex = w.texture(w.image(mr_png, name="glasses_mr"), clamp=True)
    mat = w.textured_material("glasses", tex, alpha_mode="OPAQUE", roughness=1.0, metallic=1.0)
    from pygltflib import TextureInfo

    w.gltf.materials[mat].pbrMetallicRoughness.metallicRoughnessTexture = TextureInfo(index=mr_tex, texCoord=0)
    lens = st.lens
    lens_mat = w.material("glasses_lens", lens.get("tint", "#e8eef2"), 0.05)
    m = w.gltf.materials[lens_mat]
    m.alphaMode, m.doubleSided = "BLEND", True
    m.pbrMetallicRoughness.baseColorFactor = [*srgb_to_linear(lens.get("tint", "#e8eef2"))[:3], float(lens.get("opacity", 0.04))]

    def prim(sel):
        used, local = np.unique(triangles[sel], return_inverse=True)
        p = bound.positions[used].astype(np.float32)
        nrm = vertex_normals(bound.positions.astype(np.float64), triangles[sel])[used].astype(np.float32)
        return p, nrm, local.reshape(-1, 3).astype(np.uint32), uvs[used].astype(np.float32), [bound.deltas[k][used].astype(np.float32) for k in names]

    fp, fn, fi, fu, fd = prim(~lens_mask)
    lp, ln, li, lu, ld = prim(lens_mask)
    mesh = w.mesh("glasses", positions=fp, normals=fn, indices=fi, material=mat, target_deltas=fd, target_names=names, uvs=fu,
                  extra_primitives=[{"positions": lp, "normals": ln, "indices": li, "material": lens_mat, "target_deltas": ld, "uvs": lu}])
    OUT.mkdir(parents=True, exist_ok=True)
    raw, dst = OUT / f"{st.id}.raw.glb", MODELS / f"{st.id}.glb"
    w.finish(raw, roots=[w.node("glasses", mesh=mesh)])
    gltfpack(raw, dst, *GLASSES_GLTFPACK_FLAGS)
    rename_mesh(dst, "glasses")
    entry = {"id": st.id, "label": st.label, "file": f"addons/glasses/{st.id}.glb", "thumb": f"addons/glasses/thumbs/{st.id}.webp",
             "vertices": int(len(fp) + len(lp)), "triangles": int(len(fi) + len(li)), "bytes": int(dst.stat().st_size), "targets": len(names),
             "author": "face-to-voice (generated)", "pack": "generated", "natural": main_hex, "lum": {"median": 0.0, "p98": 0.0},
             "alphaCutoff": 0.5, "tint": False,
             "glasses": {"kind": st.kind, "shape": st.shape,
                         "lens": {"tint": lens.get("tint", "#e8eef2"), "opacity": lens.get("opacity", 0.04),
                                  "gradient": lens.get("gradient", 0.0), "mirror": lens.get("mirror", 0.0)},
                         "acetate": st.kind in ("acetate", "browline")}}
    return entry, len(names)


def rename_mesh(path: Path, name: str) -> None:
    """gltfpack drops mesh names even with -kn; put ours back by editing the GLB's JSON chunk in
    place (pygltflib's save_binary would re-embed the image and grow the file by its size)."""
    data = path.read_bytes()
    magic, version, _length = struct.unpack_from("<4sII", data, 0)
    json_len, json_type = struct.unpack_from("<II", data, 12)
    if magic != b"glTF" or version != 2 or json_type != 0x4E4F534A:
        raise ValueError(f"{path} is not a GLB 2.0 file")
    doc = json.loads(data[20 : 20 + json_len])
    for m in doc.get("meshes", []):
        m["name"] = name
    body = json.dumps(doc, separators=(",", ":")).encode()
    body += b" " * (-len(body) % 4)
    rest = data[20 + json_len :]  # the BIN chunk, untouched
    out = struct.pack("<4sII", b"glTF", 2, 12 + 8 + len(body) + len(rest)) + struct.pack("<II", len(body), json_type) + body + rest
    path.write_bytes(out)


def thumbnail(st: Style, ctx, placement, triangles, uvs, lens_mask, path) -> None:
    """A quick pyvista thumbnail (the app's own shots are taken by the e2e scripts)."""
    import pyvista as pv

    from .render import HeadRenderer

    r = HeadRenderer(ctx.gnm, size=256)
    r.plotter.set_background("#f5f3f1")
    colour = np.asarray(Image.open(io.BytesIO(atlas(st)[0])).convert("RGB")) / 255
    hpx, wpx = colour.shape[:2]
    p = placement.bound.positions
    sel = ~lens_mask
    faces = np.hstack([np.full((sel.sum(), 1), 3), triangles[sel]]).ravel()
    mesh = pv.PolyData(p, faces)
    cu = np.clip((uvs[:, 0] * wpx).astype(int), 0, wpx - 1)
    cv = np.clip((uvs[:, 1] * hpx).astype(int), 0, hpx - 1)
    mesh.point_data["rgb"] = (colour[cv, cu] * 255).astype(np.uint8)
    r.plotter.add_mesh(mesh, scalars="rgb", rgb=True, smooth_shading=True, specular=0.6, specular_power=40)
    lf = np.hstack([np.full((lens_mask.sum(), 1), 3), triangles[lens_mask]]).ravel()
    r.plotter.add_mesh(pv.PolyData(p, lf), color=st.lens.get("tint", "#e8eef2"), opacity=max(0.15, float(st.lens.get("opacity", 0.04))), smooth_shading=True)
    r.look((0.0, 0.3, 0.06), 0.36, 25)
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(".png")
    r.screenshot(tmp)
    Image.open(tmp).convert("RGB").resize((128, 128), Image.LANCZOS).save(path, "WEBP", quality=85)
    tmp.unlink()


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("ids", nargs="*")
    args = ap.parse_args()
    styles = load_styles()
    ids = args.ids or list(styles)
    ctx = head_context()
    MODELS.mkdir(parents=True, exist_ok=True)
    index_path = MODELS / "index.json"
    index = json.loads(index_path.read_text())
    entries = {e["id"]: e for e in index["styles"] if e.get("pack") == "generated"}
    for sid in ids:
        t = time.time()
        st = styles[sid]
        pos, tris, uvs, lens, proxy = assemble(st, ctx)
        placement = fit(st, ctx, pos, tris[proxy])
        entry, n_targets = write(st, placement, tris, uvs, lens)
        thumb = MODELS / "thumbs" / f"{sid}.webp"
        if not thumb.exists():  # a stand-in only: the picker's thumbnails are shot in the app and must not be overwritten
            thumbnail(st, ctx, placement, tris, uvs, lens, thumb)
        rep = placement.report
        entries[sid] = entry
        print(f"  {sid}: {entry['vertices']} verts, {entry['triangles']} tris, {n_targets} targets, {entry['bytes'] / 1000:.0f} KB; "
              f"seat {rep['seat_mm']} mm, splay {rep['splay']}, tilt {rep['tilt_deg']}°, front {rep['front_width_mm']} mm, "
              f"gaps nose {rep['front_gap_mm']} / arm {rep['arm_gap_mm']} / ear {rep['ear_gap_mm']} mm ({time.time() - t:.0f} s)")
    order = list(styles)
    for sid in [k for k in entries if k not in styles]:  # styles dropped from the config: their files go too
        for rel in (entries[sid]["file"], entries[sid]["thumb"]):
            (ADDONS_MODELS_DIR.parent / rel).unlink(missing_ok=True)
        print("  removed", sid)
    index["styles"] = [entries[k] for k in order if k in entries]
    index["licence"] = LICENCE
    index_path.write_text(json.dumps(index, indent=2, ensure_ascii=False) + "\n")
    print(f"index: {len(index['styles'])} generated styles")
