"""Random face on the Feature sliders: split a raw random face into Feature slider values plus a small raw remainder.

The web app's Random face draws the raw head_* sliders (a believable face: GNM's own statistics). Those sliders sit
in the collapsed Advanced section, so the Feature sliders (Nose width, Jaw width, …) would not move. Both kinds of
slider are linear in the skin, so the same face can be written as Feature slider values s plus a raw remainder r:

    min ‖ raw face − s·Features − r·Raw ‖²  +  λ ‖ r·Raw ‖²     (outer skin, millimetres)

λ (`PREFER_FEATURES`) shifts the face onto the Feature sliders. They cannot reproduce everything exactly (each
Feature direction also uses head components that are not shipped as sliders), so a larger λ moves more onto them
but changes the face more and makes it less typical; 0.01 keeps the face within ~1 mm of the draw.

The solution is linear in the draw w: s = w P, r = w Q, so the web app turns a draw into slider values with two small
products, and Distinctiveness (which scales w) scales s and r with it. Written to web/src/data/random.json by
`uv run update-sliders` / `uv run export`; the printout says how much of a random face the Features carry.
"""
from __future__ import annotations

import json

import numpy as np

from . import semantic
from .gnm import GNM, REPO_DIR

RANDOM_JSON = REPO_DIR / "web" / "src" / "data" / "random.json"
PREFER_FEATURES = 0.01  # λ above, relative to the mean squared size of the slider directions


def split_matrices(gnm: GNM, sol, sigma_scale: float) -> tuple[list[str], list[str], np.ndarray, np.ndarray, dict]:
    ext = gnm.vertex_groups["skin_exterior"]
    raw = sol.shipped  # head_* sliders the web app ships
    Braw = np.stack([gnm.identity_basis[gnm.identity_names.index(c)][ext].ravel() * sigma_scale for c in raw]).astype(np.float64)
    ship = semantic.shipped_ids(semantic.load_config())
    keep = [k for k, sid in enumerate(sol.ids) if sid in ship]  # the Feature sliders the app has
    feats = [semantic.TARGET_PREFIX + sol.ids[k] for k in keep]
    M = np.stack([sol.delta(gnm, k)[ext].ravel() for k in keep]).astype(np.float64)
    X = np.vstack([M, Braw])
    XX = X @ X.T
    scale = np.trace(XX) / len(XX)
    penalty = np.diag([1e-6] * len(feats) + [PREFER_FEATURES] * len(raw)) * scale  # (tiny ridge on the Features)
    C = Braw @ X.T @ np.linalg.inv(XX + penalty)  # (R, S + R): draw -> [features, raw remainder]
    P, Q = C[:, :len(feats)], C[:, len(feats):]
    # how well it works on random faces drawn like the web app does (z × 0.33 weight ≈ 1σ)
    rng = np.random.default_rng(3)
    W = np.clip(rng.standard_normal((500, len(raw))) * 0.33, -0.8, 0.8)
    D = W @ Braw
    S = W @ P
    R = W @ Q
    E = D - S @ M - R @ Braw
    stats = {
        "features_share": float(1 - ((D - S @ M) ** 2).sum() / (D ** 2).sum()),  # the face carried by the Features alone
        "rms_error_mm": float(np.sqrt((E ** 2).reshape(len(W), -1, 3).sum(-1).mean()) * 1000),
        "max_error_mm": float(np.sqrt((E ** 2).reshape(len(W), -1, 3).sum(-1)).max() * 1000),
        "feature_abs_p99": float(np.quantile(np.abs(S), 0.99)),
    }
    return raw, feats, P, Q, stats


def write(gnm: GNM, sol, sigma_scale: float) -> dict:
    raw, feats, P, Q, stats = split_matrices(gnm, sol, sigma_scale)
    doc = {
        "note": "generated by pipeline random_split.py: Random face = draw w over `raw`; features s = w·P, raw remainder r = w·Q",
        "raw": raw, "features": feats,
        "P": [[round(float(v), 5) for v in row] for row in P],
        "Q": [[round(float(v), 5) for v in row] for row in Q],
        "stats": stats,
    }
    RANDOM_JSON.write_text(json.dumps(doc) + "\n")
    return stats
