"""Semantic identity sliders: one slider ≈ one facial feature (nose width, jaw width, …).

GNM's identity components are PCA modes, and each one changes many features at once. A semantic
slider is instead ONE direction `u` over all 170 head_* components. It is solved so that it changes
its own measurement a lot (e.g. the distance between the two alare points = nose width), keeps every
other slider's measurement where it was, and barely moves the face outside its own region.

GNM is linear, so every measurement is (nearly) linear in the coefficients c (σ units):

    m(c) ≈ m(0) + J c        J: (K measurements × 170 components), millimetres per σ

For slider k we minimise

    w_own (J_k c − δ)²  +  w_cross Σ_{j≠k, not free} (J_j c)²  +  cᵀ (I + λ_out Q_out + λ_sym Q_sym) c

  I      the model's own prior (coefficients are N(0, 1)): prefer the most likely face change
  Q_out  mean-square displacement outside the slider's region (mm², soft edge falloff_mm)
  Q_sym  mean-square left/right asymmetry of the displacement (mm²)

The own term has rank one, so (Sherman–Morrison) the direction does not depend on w_own or δ:

    u ∝ N⁻¹ J_kᵀ,     N = I + λ_out Q_out + λ_sym Q_sym + w_cross Σ_{j≠k} J_jᵀ J_j

Scale: at morph weight ±1 the feature sits at ±`target_pop_sigma` population standard deviations
(the measurement's σ over GNM faces is ‖J_k‖, since coefficients are N(0, 1)), so the slider spans
"narrow … wide as real people are". The coefficient vector is capped at `max_sigma` (Mahalanobis
length; a typical random face lies ~13σ from the mean in 170 dimensions), which keeps expensive,
highly constrained directions from leaving the model's statistics. `scale_sigma` on a slider
overrides both.

Config: config/semantic_sliders.toml. Commands (run from /pipeline):
    uv run semantic-landmarks [--write]   propose landmark vertices and render out/semantic/landmarks.png
    uv run semantic-report [--check]      solve, then write out/semantic/report.md, sheet.png, directions.npz
"""
from __future__ import annotations

import argparse
import json
import re
import time
import tomllib
from collections.abc import Callable
from dataclasses import dataclass, field
from pathlib import Path

import numpy as np
from scipy.spatial import cKDTree

from .export_glb import vertex_normals
from .gnm import GNM, OUT_DIR, PIPELINE_DIR

CONFIG = PIPELINE_DIR / "config" / "semantic_sliders.toml"
SEM_OUT = OUT_DIR / "semantic"
TARGET_PREFIX = "sem_"
MIDLINE_X = 5e-4  # |x| below this = on the face's midline (GNM's midline vertices sit at |x| ≤ 1e-4)
LANDMARKS_BEGIN = "# --- landmarks: generated by `uv run semantic-landmarks --write`; edit the indices freely ---"
LANDMARKS_END = "# --- end landmarks ---"


# --- landmarks -----------------------------------------------------------------------------------


@dataclass
class Landmark:
    indices: list[int]  # one vertex, or a small set whose mean position is used
    rule: str  # how it was found (written as a comment next to the index)


def _ring(gnm: GNM, inner: np.ndarray) -> np.ndarray:
    """Outer-skin vertices that share a triangle with `inner` (the rim of the eye or mouth opening)."""
    ext = gnm.vertex_groups["skin_exterior"]
    touch = inner[gnm.triangles].any(axis=1)
    rim = np.unique(gnm.triangles[touch])
    return rim[ext[rim]]


def propose_landmarks(gnm: GNM) -> dict[str, Landmark]:
    """Pick anthropometric landmark vertices on the GNM template from simple geometric rules.

    Left-side points (+X is the head's left) are found by rule; the "_r" twin is the GNM mirror vertex.
    """
    T, g = gnm.template, gnm.vertex_groups
    ext = g["skin_exterior"]
    x, y, z = T[:, 0], T[:, 1], T[:, 2]
    mid = ext & (np.abs(x) < MIDLINE_X) & (z > 0.06)  # front half of the midline profile

    def pick(mask: np.ndarray, key: np.ndarray, largest: bool) -> int:
        idx = np.flatnonzero(mask)
        if not len(idx):
            raise RuntimeError("landmark rule matched no vertex")
        return int(idx[np.argmax(key[idx]) if largest else np.argmin(key[idx])])

    L: dict[str, Landmark] = {}

    def add(name: str, i: int | list[int], rule: str, mirror: bool = False) -> None:
        ids = [int(v) for v in np.atleast_1d(i)]
        if mirror:
            L[f"{name}_l"] = Landmark(ids, rule)
            L[f"{name}_r"] = Landmark([int(gnm.mirror[v]) for v in ids], "mirror of " + name + "_l")
        else:
            L[name] = Landmark(ids, rule)

    # midline profile, top to bottom
    add("trichion", pick(mid & g["forehead_region"], y, True), "forehead_region, midline, highest (hairline)")
    add("glabella", pick(mid & (y > 0.31) & (y < 0.345), z, True), "midline, y 0.310–0.345, most forward (between the brows)")
    add("nasion", pick(mid & (y > 0.285) & (y < 0.315), z, False), "midline, y 0.285–0.315, deepest (root of the nose)")
    prn = pick(mid & g["nose_region"], z, True)
    add("pronasale", prn, "nose_region, midline, most forward (nose tip)")
    sn = pick(mid & g["nose_region"], y, False)
    add("subnasale", sn, "nose_region, midline, lowest (where the nose meets the lip)")
    add("labrale_superius", pick(mid & g["upper_lip"], y, True), "upper_lip (red lip), midline, highest")
    li = pick(mid & g["lower_lip"], y, False)
    add("labrale_inferius", li, "lower_lip (red lip), midline, lowest")
    add("sublabiale", pick(mid & (y < y[li]) & (y > y[li] - 0.015), z, False), "midline, ≤15 mm below labrale_inferius, deepest (chin crease)")
    add("menton", pick(mid & g["chin_region"], y, False), "chin_region, midline, lowest")

    # eyes: the rim of the eye opening (skin next to the eye socket)
    rim = _ring(gnm, g["eye_sockets"])
    left_rim = np.zeros(len(T), bool)
    left_rim[rim[x[rim] > 0]] = True
    en = pick(left_rim, x, False)
    ex = pick(left_rim, x, True)
    add("endocanthion", en, "eye-opening rim, innermost (inner eye corner)", mirror=True)
    add("exocanthion", ex, "eye-opening rim, outermost (outer eye corner)", mirror=True)
    add("lid_upper", pick(left_rim, y, True), "eye-opening rim, highest (upper lid margin)", mirror=True)
    add("lid_lower", pick(left_rim, y, False), "eye-opening rim, lowest (lower lid margin)", mirror=True)
    add("canthi", [en, ex], "both eye corners (vertical reference for the brow)", mirror=True)
    pupil_x = float(T[ex, 0] + T[en, 0]) / 2
    brow = np.flatnonzero(g["left_brow_region"] & ext & (np.abs(x - pupil_x) < 0.003))
    add("brow", brow.tolist(), "left_brow_region within 3 mm of the eye's centre line (whole brow height)", mirror=True)
    # brow ends, for expression goals (emotions.py): inner = the 5 mm nearest the midline, outer = the last 8 mm
    brow_all = g["left_brow_region"] & ext
    bx = x[brow_all]
    add("brow_inner", np.flatnonzero(brow_all & (x < bx.min() + 0.005)).tolist(), "left_brow_region, innermost 5 mm (inner brow)", mirror=True)
    add("brow_outer", np.flatnonzero(brow_all & (x > bx.max() - 0.008)).tolist(), "left_brow_region, outermost 8 mm (brow tail)", mirror=True)

    # nose and mouth
    add("alare", pick(g["nose_region"] & ext & (y > y[sn]) & (y < y[sn] + 0.012) & (x > 0), x, True),
        "nose_region, ≤12 mm above subnasale, widest (nostril wing)", mirror=True)
    mouth_rim = _ring(gnm, g["mouth_sock"])
    left_mouth = np.zeros(len(T), bool)
    left_mouth[mouth_rim[x[mouth_rim] > 0]] = True
    add("cheilion", pick(left_mouth, x, True), "mouth-opening rim, outermost (mouth corner)", mirror=True)
    mouth_mid = np.zeros(len(T), bool)
    mouth_mid[mouth_rim[np.abs(x[mouth_rim]) < MIDLINE_X]] = True
    # by lip group, not by height: the closed lips overlap, so the upper lip's edge sits 0.8 mm BELOW the lower one's
    add("stomion_upper", pick(mouth_mid & g["upper_lip"], y, False), "mouth-opening rim, midline, on the upper lip (its inner edge)")
    add("stomion_lower", pick(mouth_mid & g["lower_lip"], y, True), "mouth-opening rim, midline, on the lower lip (its inner edge)")

    # jaw angle: just in front of the ear, where the side of the face turns into the underside of the
    # jaw (the surface normal closest to 45° outwards-and-down)
    normals = vertex_normals(T, gnm.triangles)
    corner = normals @ (np.array([1.0, -1.0, 0.0]) / np.sqrt(2))
    band = ext & (x > 0.03) & (z > 0.025) & (z < 0.05) & (y > 0.18) & (y < 0.24)
    add("gonion", pick(band, corner, True), "side of the jaw in front of the ear, normal closest to 45° out-and-down (jaw angle)", mirror=True)

    # skull
    back = ext & (np.abs(x) < MIDLINE_X) & (z < 0)
    add("vertex", pick(ext & (np.abs(x) < MIDLINE_X), y, True), "midline, highest (top of the head)")
    add("opisthocranion", pick(back & (y > 0.26) & (y < 0.36), z, False), "midline, y 0.26–0.36, furthest back (back of the skull)")
    ears = g["ears"]
    add("euryon", pick(ext & ~ears & (y > 0.30) & (x > 0), x, True), "above the ears, widest point of the skull", mirror=True)
    # cheekbones and chin
    add("zygion", pick(g["left_zygomatic_region"] & ext, x, True), "left_zygomatic_region, widest (cheekbone)", mirror=True)
    pog = pick(mid & g["chin_region"], z, True)
    add("pogonion", pog, "chin_region, midline, most forward (chin point)")
    add("chin_side", pick(g["chin_region"] & ext & (np.abs(y - y[pog]) < 0.004) & (x > 0), x, True),
        "chin_region at the chin point's height, widest", mirror=True)
    # ears: top, bottom, outermost rim point, and the ring where the ear joins the head
    left_ear = ears & ext & (x > 0)
    add("ear_top", pick(left_ear, y, True), "left ear, highest", mirror=True)
    add("ear_bottom", pick(left_ear, y, False), "left ear, lowest (lobe)", mirror=True)
    add("ear_out", pick(left_ear, x, True), "left ear, furthest out (rim)", mirror=True)
    head_skin = ext & ~ears
    root = np.unique(gnm.triangles[(ears[gnm.triangles].any(axis=1)) & (head_skin[gnm.triangles].any(axis=1))])
    root = root[left_ear[root]]
    add("ear_root", root.tolist(), "left ear vertices that touch the head skin (where the ear joins the head)", mirror=True)
    return L


def _format_landmarks(L: dict[str, Landmark]) -> str:
    lines = [LANDMARKS_BEGIN, "[landmarks]"]
    for name, lm in L.items():
        value = str(lm.indices[0]) if len(lm.indices) == 1 else "[" + ", ".join(map(str, lm.indices)) + "]"
        lines.append(f"{name} = {value}".ljust(34) + f"  # {lm.rule}")
    lines.append(LANDMARKS_END)
    return "\n".join(lines) + "\n"


def write_landmarks(L: dict[str, Landmark], path: Path = CONFIG) -> None:
    """Replace (or append) the generated [landmarks] block of the config, keeping everything else."""
    text = path.read_text()
    block = _format_landmarks(L)
    pattern = re.compile(re.escape(LANDMARKS_BEGIN) + r".*?" + re.escape(LANDMARKS_END) + r"\n?", re.S)
    text = pattern.sub(block, text) if pattern.search(text) else text.rstrip("\n") + "\n\n" + block
    path.write_text(text)


# --- config + measurements --------------------------------------------------------------------------


def load_config(path: Path = CONFIG) -> dict:
    with open(path, "rb") as f:
        cfg = tomllib.load(f)
    ids = [s["id"] for s in cfg["slider"]]
    if len(set(ids)) != len(ids):
        raise ValueError(f"duplicate slider ids in {path.name}")
    for s in cfg["slider"]:
        for f in s.get("free", []):
            if f != "*" and f not in ids:
                raise ValueError(f"{s['id']}: free = {f!r} is not a slider id")
        if s.get("bake", "auto") not in (True, False, "auto"):
            raise ValueError(f"{s['id']}: bake must be true, false or \"auto\"")
    return cfg


def config_landmarks(cfg: dict) -> dict[str, np.ndarray]:
    if "landmarks" not in cfg:
        raise SystemExit("no [landmarks] in semantic_sliders.toml yet: run `uv run semantic-landmarks --write`")
    return {k: np.atleast_1d(np.asarray(v, np.int64)) for k, v in cfg["landmarks"].items()}


AXES = {"x": 0, "y": 1, "z": 2}


@dataclass
class Measure:
    """A linearised measurement: value(P) in mm, and its gradient with respect to the vertex positions."""

    value: Callable[[np.ndarray], float]  # (V, 3) metres -> float mm
    grad: np.ndarray  # (V, 3) mm per metre of vertex movement, taken at the template


def build_measure(spec: dict, lm: dict[str, np.ndarray], gnm: GNM, normals: np.ndarray) -> Measure:
    T = gnm.template
    V = len(T)
    if "terms" in spec:
        parts = [(float(t.get("weight", 1.0)), build_measure(t, lm, gnm, normals)) for t in spec["terms"]]
        return Measure(lambda P: sum(w * m.value(P) for w, m in parts), sum(w * m.grad for w, m in parts))

    kind = spec["type"]
    if kind in ("distance", "axis"):
        pairs = [(lm[a], lm[b]) for a, b in spec["pairs"]]
        for a, b in spec["pairs"]:
            for n in (a, b):
                if n not in lm:
                    raise KeyError(f"unknown landmark {n!r}")
        grad = np.zeros((V, 3))
        if kind == "distance":
            def value(P):
                return 1000.0 * np.mean([np.linalg.norm(P[a].mean(0) - P[b].mean(0)) for a, b in pairs])
            for a, b in pairs:
                d = T[a].mean(0) - T[b].mean(0)
                u = d / np.linalg.norm(d)
                np.add.at(grad, a, 1000.0 * u / len(a) / len(pairs))
                np.add.at(grad, b, -1000.0 * u / len(b) / len(pairs))
        else:
            ax = AXES[spec["axis"]]
            def value(P):
                return 1000.0 * np.mean([P[a].mean(0)[ax] - P[b].mean(0)[ax] for a, b in pairs])
            for a, b in pairs:
                np.add.at(grad[:, ax], a, 1000.0 / len(a) / len(pairs))
                np.add.at(grad[:, ax], b, -1000.0 / len(b) / len(pairs))
        return Measure(value, grad)

    if kind == "normal":
        mask = np.zeros(V, bool)
        for grp in spec.get("groups", ["skin_exterior"]):
            mask |= gnm.vertex_groups[grp]
        mask &= gnm.vertex_groups["skin_exterior"]
        # optional bands (metres) to cut a part of the skin: y = [lo, hi], z = [lo, hi], x_abs_max = m
        for ax, key in ((1, "y"), (2, "z")):
            if key in spec:
                lo, hi = spec[key]
                mask &= (T[:, ax] >= lo) & (T[:, ax] <= hi)
        if "x_abs_max" in spec:
            mask &= np.abs(T[:, 0]) <= spec["x_abs_max"]
        if not mask.any():
            raise ValueError(f"normal measure selects no vertex: {spec}")
        idx = np.flatnonzero(mask)
        n = normals[idx]
        grad = np.zeros((V, 3))
        grad[idx] = 1000.0 * n / len(idx)
        return Measure(lambda P: 1000.0 * float(np.mean(np.einsum("ij,ij->i", P[idx] - T[idx], n))), grad)
    if kind == "balance":
        # a and b change in proportion to their own size: 0 when both grow by the same fraction
        ma, mb = build_measure(spec["a"], lm, gnm, normals), build_measure(spec["b"], lm, gnm, normals)
        a0, b0 = abs(ma.value(T)), abs(mb.value(T))
        k = (a0 + b0) / 2
        return Measure(lambda P: k * ((ma.value(P) - a0) / a0 - (mb.value(P) - b0) / b0), k * (ma.grad / a0 - mb.grad / b0))
    raise ValueError(f"unknown measure type {kind!r}")


# --- solver ------------------------------------------------------------------------------------------------


@dataclass
class Solution:
    ids: list[str]
    names: list[str]
    components: list[str]  # the identity components the directions are expressed in
    coefficients: np.ndarray  # (S, C) σ per component at morph weight 1.0
    J: np.ndarray  # (S, C) mm per σ, rows = each slider's own measurement
    pop_sigma: np.ndarray  # (S,) population σ of each measurement, mm (‖J_k‖)
    measures: list[Measure] = field(repr=False, default_factory=list)
    outside: list[np.ndarray] = field(repr=False, default_factory=list)  # (V,) outside weight per slider
    free: list[list[str]] = field(default_factory=list)  # per slider: measurements it may change (nested)
    guard_ids: list[str] = field(default_factory=list)  # measurements every slider holds fixed (not sliders)
    guard_measures: list[Measure] = field(repr=False, default_factory=list)
    baked: list[bool] = field(default_factory=list)  # True: own morph target; False: a mix of the shipped raw targets
    shipped: list[str] = field(default_factory=list)  # the raw head_* components head.glb ships (runtime mixes use these)
    choice: list[dict] = field(default_factory=list)  # per slider: how the baked and the runtime version compared
    held: list[bool] = field(default_factory=list)  # False: other sliders may change this measurement

    def combo(self, k: int, sigma_scale: float) -> dict[str, float]:
        """Runtime slider k as head.glb morph weights of the raw targets at weight 1.0 (weight = σ / sigma_scale)."""
        return {c: round(float(self.coefficients[k][self.components.index(c)]) / sigma_scale, 6) for c in self.shipped
                if abs(self.coefficients[k][self.components.index(c)]) > 1e-9}

    def delta(self, gnm: GNM, k: int) -> np.ndarray:
        """(V, 3) metres at morph weight 1.0 for slider k (exact: GNM is linear)."""
        idx = [gnm.identity_names.index(c) for c in self.components]
        return np.tensordot(self.coefficients[k].astype(np.float32), gnm.identity_basis[idx], axes=1)

    def joint_delta(self, gnm: GNM, k: int) -> np.ndarray:
        """(4, 3) metres at morph weight 1.0 — how the joints (eye pivots) move with slider k."""
        idx = [gnm.identity_names.index(c) for c in self.components]
        return np.tensordot(self.coefficients[k].astype(np.float32), gnm.joint_identity_basis[idx], axes=1)


def outside_weight(gnm: GNM, groups: list[str], falloff_mm: float, y_band: list[float] | None = None) -> np.ndarray:
    """1 far from the region, 0 inside it, a linear ramp over falloff_mm in between. `y_band` = [lo, hi] (metres):
    only the part of the groups at that height (GNM has no neck group: the neck is skin between two heights)."""
    inside = np.zeros(len(gnm.template), bool)
    for grp in groups:
        inside |= gnm.vertex_groups[grp]
    if y_band is not None:
        inside &= (gnm.template[:, 1] >= y_band[0]) & (gnm.template[:, 1] <= y_band[1])
    dist, _ = cKDTree(gnm.template[inside]).query(gnm.template)
    return np.clip(dist / (falloff_mm / 1000.0), 0.0, 1.0)


def shipped_components(gnm: GNM) -> list[str]:
    """The raw head_* identity components baked into head.glb (config/components.toml)."""
    from .export_glb import load_config as load_components

    return [c for c in load_components()["identity"]["components"] if gnm.region_of(c) == "head"]


# A runtime mix of the shipped raw targets replaces a baked target when it does nearly as well (costs no bytes):
COMBO_MIN_OWN = 0.85  # its own change is at least 85% of the baked direction's
COMBO_MAX_OUTSIDE = 1.3  # and it moves the skin outside the region at most 30% more (or 0.15 mm RMS more)


def solve(gnm: GNM, cfg: dict) -> Solution:
    sv = cfg["solver"]
    comps = [n for n in gnm.identity_names if gnm.region_of(n) == sv.get("components", "head")]
    cidx = [gnm.identity_names.index(c) for c in comps]
    B = gnm.identity_basis[cidx].astype(np.float64) * 1000.0  # (C, V, 3) mm per σ
    C = len(comps)
    lm = config_landmarks(cfg)
    normals = vertex_normals(gnm.template, gnm.triangles)
    sliders = cfg["slider"]
    measures = [build_measure(s["measure"], lm, gnm, normals) for s in sliders]
    guards = cfg.get("guard", [])
    guard_measures = [build_measure(g["measure"], lm, gnm, normals) for g in guards]

    def jac(m: Measure) -> np.ndarray:
        return np.tensordot(B, m.grad / 1000.0, axes=([1, 2], [0, 1]))  # (C,) mm per σ

    J = np.stack([jac(m) for m in measures])  # (S, C)
    # what the OTHER sliders hold fixed for each slider: its own measurement, unless it names another (`held_measure`:
    # the slider aims at a new measurement while the others keep holding the old one, so their solutions stay put)
    Jh = np.stack([jac(build_measure(s["held_measure"], lm, gnm, normals)) if "held_measure" in s else J[k]
                   for k, s in enumerate(cfg["slider"])])
    G = np.stack([jac(m) for m in guard_measures]) if guards else np.zeros((0, C))

    # everything is measured on the outer skin (eyeballs, teeth and the mouth interior are free)
    ext = np.flatnonzero(gnm.vertex_groups["skin_exterior"])
    Bx = B[:, ext, :]  # (C, N, 3)
    Bf = Bx.reshape(C, -1)
    mirror = gnm.mirror[ext]
    pos = {v: i for i, v in enumerate(ext)}
    paired = np.array([m in pos for m in mirror])
    mi = np.array([pos[m] for m in mirror[paired]])
    flip = np.array([-1.0, 1.0, 1.0])
    asym = (Bx[:, paired, :] - Bx[:, mi, :] * flip).reshape(C, -1)
    Q_sym = asym @ asym.T / paired.sum()

    shipped = shipped_components(gnm)
    ship_idx = np.array([comps.index(c) for c in shipped])
    coeffs = np.zeros((len(sliders), C))
    outside, baked, choice = [], [], []
    ids = [s["id"] for s in sliders]
    held = [s.get("held", True) for s in sliders]  # held = false: nobody else has to keep this one fixed (e.g. head size)
    for k, s in enumerate(sliders):
        w_out = outside_weight(gnm, s["region"], float(s.get("falloff_mm", sv["falloff_mm"])), s.get("region_y"))
        outside.append(w_out)
        w = np.repeat(w_out[ext] ** 2, 3)
        Q_out = (Bf * w) @ Bf.T / max(w_out[ext].sum(), 1.0)
        free = set(s.get("free", []))
        others = [] if "*" in free else [j for j, o in enumerate(ids) if j != k and o not in free and held[j]]
        Jo = Jh[others]  # (O, C) the measurements this slider must leave alone
        H = np.stack([jac(build_measure(h, lm, gnm, normals)) for h in s.get("hold", [])]) if s.get("hold") else np.zeros((0, C))
        N = (np.eye(C)
             + float(s.get("lambda_out", sv["lambda_out"])) * Q_out
             + float(s.get("lambda_sym", sv["lambda_sym"])) * Q_sym
             + float(sv["w_cross"]) * Jo.T @ Jo
             + float(sv.get("w_guard", sv["w_cross"])) * G.T @ G
             + float(s.get("w_hold", sv.get("w_guard", sv["w_cross"]))) * H.T @ H)

        full = _direction(N, J[k], np.arange(C), s, sv)
        mix = _direction(N, J[k], ship_idx, s, sv)
        qf, qm = _quality(full, J[k], Jo, G, Q_out), _quality(mix, J[k], Jo, G, Q_out)
        good_mix = (abs(qm["own"]) >= COMBO_MIN_OWN * abs(qf["own"])
                    and qm["outside"] <= max(COMBO_MAX_OUTSIDE * qf["outside"], qf["outside"] + 0.15)
                    and abs(qm["own"]) >= 4 * qm["cross"]
                    and qm["guard"] <= 0.5 * MAX_GUARD_MM)
        bake = s.get("bake", "auto")
        use_mix = (bake is False) or (bake == "auto" and good_mix)
        coeffs[k] = mix if use_mix else full
        baked.append(not use_mix)
        choice.append({"baked": qf, "runtime": qm, "runtime_ok": bool(good_mix), "bake": bake})
    return Solution(ids, [s["name"] for s in sliders], comps, coeffs, J, np.linalg.norm(J, axis=1), measures, outside,
                    [ids if "*" in s.get("free", []) else list(s.get("free", [])) for s in sliders],
                    [g["id"] for g in guards], guard_measures, baked, shipped, choice, held)


def _direction(N: np.ndarray, Jk: np.ndarray, idx: np.ndarray, s: dict, sv: dict) -> np.ndarray:
    """Slider `s`'s solved direction on the components `idx` (the rest zero), scaled to weight 1.0."""
    u = np.zeros(len(Jk))
    u[idx] = np.linalg.solve(N[np.ix_(idx, idx)], Jk[idx])
    u /= np.linalg.norm(u)  # unit Mahalanobis length (coefficients are N(0, 1))
    if "scale_sigma" in s:  # hand override: weight 1.0 = exactly this many σ along u
        length = float(s["scale_sigma"])
    else:  # weight 1.0 = the feature at ±target_pop_sigma of the population, within max_sigma
        length = min(float(sv["target_pop_sigma"]) * np.linalg.norm(Jk) / float(Jk @ u), float(sv["max_sigma"]))
    return length * u


def _quality(c: np.ndarray, Jk: np.ndarray, Jo: np.ndarray, G: np.ndarray, Q_out: np.ndarray) -> dict:
    """Linearised effect of coefficients `c`: own change, largest held change, outside RMS and largest guard (mm)."""
    cross = np.abs(Jo @ c).max() if len(Jo) else 0.0
    guard = float(np.abs(G @ c).max()) if len(G) else 0.0
    return {"own": float(Jk @ c), "cross": float(cross), "outside": float(np.sqrt(max(c @ Q_out @ c, 0.0))), "guard": guard}


# --- report ------------------------------------------------------------------------------------------------


def evaluate(gnm: GNM, sol: Solution) -> list[dict]:
    """Measure what each slider really does at +1 and -1 (exact geometry, not the linearisation)."""
    ext = gnm.vertex_groups["skin_exterior"]
    base = np.array([m.value(gnm.template) for m in sol.measures])
    rows = []
    for k, sid in enumerate(sol.ids):
        d = sol.delta(gnm, k)
        plus = np.array([m.value(gnm.template + d) for m in sol.measures]) - base
        minus = np.array([m.value(gnm.template - d) for m in sol.measures]) - base
        change = (plus - minus) / 2  # symmetric estimate; the linear part
        linear = sol.J[k] @ sol.coefficients[k]
        cross = np.abs(change.copy())
        cross[k] = 0
        j = int(np.argmax(cross))
        strict = cross.copy()  # leave out the measurements this slider is allowed to change (free = nested)
        for f in sol.free[k]:
            strict[sol.ids.index(f)] = 0
        for i, h in enumerate(sol.held):
            if not h:
                strict[i] = 0
        js = int(np.argmax(strict))
        guard = [abs((gm.value(gnm.template + d) - gm.value(gnm.template - d)) / 2) for gm in sol.guard_measures]
        far = ext & (sol.outside[k] >= 0.999)
        mag = np.linalg.norm(d, axis=1) * 1000.0
        rows.append({
            "id": sid, "name": sol.names[k],
            "own_mm": float(change[k]), "plus_mm": float(plus[k]), "minus_mm": float(minus[k]),
            "pop_sigma_mm": float(sol.pop_sigma[k]),
            "efficiency": float(change[k] / (np.linalg.norm(sol.coefficients[k]) * sol.pop_sigma[k])),
            "cross_mm": float(cross[j]), "cross_id": sol.ids[j],
            "cross_strict_mm": float(strict[js]), "cross_strict_id": sol.ids[js],
            "ratio": float(abs(change[k]) / max(cross[j], 1e-9)),
            "outside_rms_mm": float(np.sqrt(np.mean(mag[far] ** 2))) if far.any() else 0.0,
            "outside_max_mm": float(mag[far].max()) if far.any() else 0.0,
            "max_mm": float(mag[ext].max()),
            "lin_error": float(abs(linear - change[k]) / max(abs(change[k]), 1e-9)),
            "asym": float(abs(plus[k] + minus[k]) / max(abs(change[k]), 1e-9)),  # +1 vs -1 imbalance
            "sigma": float(np.linalg.norm(sol.coefficients[k])),
            "guards_mm": {gid: float(v) for gid, v in zip(sol.guard_ids, guard)},
            "all_mm": change.tolist(),
        })
    return rows


def coverage(gnm: GNM, sol: Solution, samples: int = 400, seed: int = 7) -> dict:
    """How much of what the raw sliders can do the semantic sliders can do too.

    Random faces over the shipped raw head_* components (z ~ N(0, 1), the Advanced sliders' space) are fitted
    with the semantic directions by least squares (sliders unbounded); coverage = 1 − residual² / total² of the
    outer-skin displacement. Also per raw component: how much of that one slider's shape the semantic set reproduces."""
    ext = gnm.vertex_groups["skin_exterior"]
    ship = [gnm.identity_names.index(c) for c in sol.shipped]
    Braw = gnm.identity_basis[ship][:, ext, :].reshape(len(ship), -1).astype(np.float64)  # (R, 3N)
    M = np.stack([sol.delta(gnm, k)[ext].ravel() for k in range(len(sol.ids))]).astype(np.float64)  # (S, 3N)
    G = M @ M.T + 1e-12 * np.eye(len(M))

    def explained(D: np.ndarray) -> np.ndarray:  # D (n, 3N) -> fraction of each row reproduced
        W = np.linalg.solve(G, M @ D.T)  # (S, n)
        R = D - W.T @ M
        return 1.0 - (R ** 2).sum(1) / (D ** 2).sum(1)

    rng = np.random.default_rng(seed)
    Z = rng.standard_normal((samples, len(ship)))
    D = Z @ Braw
    W = np.linalg.solve(G, M @ D.T)
    total = float(1.0 - ((D - W.T @ M) ** 2).sum() / (D ** 2).sum())
    per = explained(Braw)
    return {"random_faces": total, "per_raw": {c: float(v) for c, v in zip(sol.shipped, per)}}


def write_report(rows: list[dict], sol: Solution, path: Path, cover: dict | None = None) -> str:
    lines = [
        "# Semantic sliders — what each one does at weight +1",
        "",
        "own = change of the slider's own measurement (mm, mean of +1 and −1); "
        "cross = the largest change of any other measurement; outside = movement of the skin beyond the "
        "slider's region (+ falloff); guards = the largest change of a guard measurement (" + ", ".join(sol.guard_ids) + ", held "
        "fixed by every slider); length = Mahalanobis length of the direction at +1; efficiency = own change ÷ what the model allows at this σ "
        "(‖u‖ × population σ); lin. = linearisation error.",
        "",
        "shipped as = baked (its own morph target in head.glb) or runtime (a mix of the raw head_* targets, no extra "
        "bytes; chosen when it does nearly as well).",
        "",
        "| slider | shipped as | own Δ mm (pop. σ) | largest cross Δ mm (which) | own / cross | cross, nested excluded | guards Δ mm | outside RMS / max mm | max anywhere mm | length σ | efficiency | lin. |",
        "|---|---|---:|---|---:|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for k, r in enumerate(rows):
        lines.append(
            f"| {r['name']} | {'baked' if sol.baked[k] else 'runtime'} | {r['own_mm']:+.2f} ({r['own_mm'] / r['pop_sigma_mm']:.1f}σ) | {r['cross_mm']:.2f} ({r['cross_id']}) | "
            f"{r['ratio']:.1f}× | {r['cross_strict_mm']:.2f} ({r['cross_strict_id']}) | "
            f"{max(r['guards_mm'].values(), default=0.0):.2f} | "
            f"{r['outside_rms_mm']:.2f} / {r['outside_max_mm']:.2f} | {r['max_mm']:.2f} | {r['sigma']:.1f} | "
            f"{r['efficiency'] * 100:.0f}% | {r['lin_error'] * 100:.1f}% |")
    if cover:
        lines += ["", "## Coverage of the raw sliders", "",
                  f"Random faces over the {len(sol.shipped)} raw head sliders: the semantic sliders reproduce "
                  f"**{cover['random_faces'] * 100:.0f}%** of the skin movement (least squares, sliders unbounded).", "",
                  "| raw slider | reproduced |", "|---|---:|"]
        for c, v in sorted(cover["per_raw"].items(), key=lambda kv: kv[1]):
            lines.append(f"| {c} | {v * 100:.0f}% |")
    lines += ["", "## Cross-talk matrix (mm change of each measurement, columns, when a slider, rows, is at +1)", ""]
    short = [i[:10] for i in sol.ids]
    lines.append("| slider | " + " | ".join(short) + " |")
    lines.append("|---|" + "---:|" * len(short))
    for r in rows:
        cells = [f"**{v:+.2f}**" if i == sol.ids.index(r["id"]) else f"{v:+.2f}" for i, v in enumerate(r["all_mm"])]
        lines.append(f"| {r['name']} | " + " | ".join(cells) + " |")
    text = "\n".join(lines) + "\n"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)
    return text


# quality gates: the own change must dominate every non-nested measurement,
# guards must hold, and the linear model must describe the geometry
MIN_RATIO = 4.0  # own change ≥ 4 × the largest other (non-nested) change
MAX_GUARD_MM = 0.2
MAX_LIN_ERROR = 0.05


def check(rows: list[dict]) -> list[str]:
    out = []
    for r in rows:
        if abs(r["own_mm"]) < MIN_RATIO * r["cross_strict_mm"]:
            out.append(f"{r['id']}: own {r['own_mm']:+.2f} mm < {MIN_RATIO:g}× {r['cross_strict_id']} {r['cross_strict_mm']:.2f} mm")
        for gid, v in r["guards_mm"].items():
            if v > MAX_GUARD_MM:
                out.append(f"{r['id']}: guard {gid} moved {v:.2f} mm")
        if r["lin_error"] > MAX_LIN_ERROR:
            out.append(f"{r['id']}: linearisation error {r['lin_error'] * 100:.1f}%")
    return out


# --- rendering ----------------------------------------------------------------------------------------------

# (focal point, distance) for a 28° vertical field of view; eyes at y≈0.30, mouth y≈0.23, nose tip z≈0.145
FRAMES = {
    "face": ((0.0, 0.268, 0.07), 0.62),
    "eyes": ((0.0, 0.305, 0.10), 0.28),
    "nose": ((0.0, 0.272, 0.11), 0.26),
    "mouth": ((0.0, 0.215, 0.10), 0.30),
    "jaw": ((0.0, 0.235, 0.05), 0.55),
}
VIEW_YAW = {"front": 0.0, "quarter": 40.0, "profile": 90.0}


def head_renderer(gnm: GNM, size: int):
    """An off-screen render.HeadRenderer with `size` px square frames."""
    from .render import HeadRenderer

    return HeadRenderer(gnm, size=size)


def label_font(size: int):
    """PIL's default font at `size` px, for sheet captions."""
    from PIL import ImageFont

    return ImageFont.load_default(size=size)


def render_landmarks(gnm: GNM, lm: dict[str, np.ndarray], cfg: dict, path: Path, size: int = 640) -> None:
    """Six views of the template with every landmark marked and labelled, plus the 'normal' vertex groups."""
    from PIL import Image, ImageDraw

    r = head_renderer(gnm, size)
    r.set_positions(gnm.template)
    normals = vertex_normals(gnm.template, gnm.triangles)
    groups = sorted({g for s in cfg["slider"] for g in _normal_groups(s["measure"])})
    patch = np.zeros(len(gnm.template), bool)
    for grp in groups:
        patch |= gnm.vertex_groups[grp]
    patch &= gnm.vertex_groups["skin_exterior"]

    panels = [("front, whole face", "face", 0.0), ("profile (left side)", "face", 90.0), ("eyes and brows", "eyes", 0.0),
              ("nose, three-quarter", "nose", 35.0), ("mouth and chin, three-quarter", "mouth", 35.0), ("jaw, three-quarter", "jaw", 45.0)]
    tiles = []
    for title, frame, yaw in panels:
        focal, dist = FRAMES[frame]
        r.look(focal, dist, yaw)
        cam = np.array(r.plotter.camera.position)
        r.clear_overlays()
        # only label points facing the camera (the others would show through the head)
        pts, labels = [], []
        for name, ids in lm.items():
            p = gnm.template[ids].mean(0)
            n = normals[ids].mean(0)
            view = (cam - p) / np.linalg.norm(cam - p)
            if np.dot(n, view) < -0.35:  # clearly facing away (lid margins are allowed to graze)
                continue
            if len(ids) > 1:
                r.add_points(gnm.template[ids], "#4fc3f7", size=6)
            pts.append(p)
            labels.append(name)
        side = np.flatnonzero(patch)
        facing = side[np.einsum("ij,ij->i", normals[side], cam - gnm.template[side]) > 0]
        if len(facing):
            r.add_points(gnm.template[facing], "#81c784", size=3)
        if pts:
            r.add_points(np.array(pts), "#ff5252", size=11, labels=labels, font_size=13 if frame == "face" else 15)
        tile = SEM_OUT / f"_landmarks_{frame}_{int(yaw)}.png"
        r.screenshot(tile)
        img = Image.open(tile).convert("RGB")
        ImageDraw.Draw(img).text((10, 8), title, fill="white", font=label_font(18))
        tiles.append(img)
        tile.unlink()
    r.clear_overlays()
    cols = 3
    sheet = Image.new("RGB", (cols * size, ((len(tiles) + cols - 1) // cols) * size), "#2b2b2b")
    for i, t in enumerate(tiles):
        sheet.paste(t, ((i % cols) * size, (i // cols) * size))
    legend = ImageDraw.Draw(sheet)
    legend.text((10, sheet.height - 26), "red = landmark vertex · blue = vertex set (mean used) · green = vertices of a 'normal' (fullness) measurement",
                fill="#dddddd", font=label_font(15))
    path.parent.mkdir(parents=True, exist_ok=True)
    sheet.save(path)


def _normal_groups(spec: dict) -> list[str]:
    if "terms" in spec:
        return [g for t in spec["terms"] for g in _normal_groups(t)]
    return list(spec.get("groups", [])) if spec.get("type") == "normal" else []


def render_sheet(gnm: GNM, sol: Solution, cfg: dict, rows: list[dict], path: Path, size: int = 300) -> None:
    """One row per slider: −1 / 0 / +1 in the slider's own view, then a heat map of where it moves the face."""
    from PIL import Image, ImageDraw

    r = head_renderer(gnm, size)
    label_w = 250
    sheet = Image.new("RGB", (label_w + 4 * size, len(sol.ids) * size + 34), "#1f1f1f")
    draw = ImageDraw.Draw(sheet)
    for c, head in enumerate(["-1", "0", "+1", "where it moves (dark 0 mm .. bright max)"]):
        draw.text((label_w + c * size + 10, 8), head, fill="white", font=label_font(17))
    for k, s in enumerate(cfg["slider"]):
        d = sol.delta(gnm, k)
        focal, dist = FRAMES[s.get("frame", "face")]
        yaw = VIEW_YAW[s.get("view", "front")]
        y0 = 34 + k * size
        for c, w in enumerate((-1.0, 0.0, 1.0)):
            r.show_heat(None)
            r.set_positions(gnm.template + np.float32(w) * d)
            r.look(focal, dist, yaw)
            tile = SEM_OUT / "_tile.png"
            r.screenshot(tile)
            sheet.paste(Image.open(tile).convert("RGB"), (label_w + c * size, y0))
        mag = np.linalg.norm(d, axis=1) * 1000.0
        r.set_positions(gnm.template)
        r.show_heat(mag, (0.0, float(mag.max())))
        r.look(FRAMES["face"][0], FRAMES["face"][1], 30.0)
        r.screenshot(tile)
        sheet.paste(Image.open(tile).convert("RGB"), (label_w + 3 * size, y0))
        row = rows[k]
        text = [s["name"], f"-1 {s.get('low', '')}", f"+1 {s.get('high', '')}",
                f"own change {row['own_mm']:+.1f} mm", f"largest other {row['cross_mm']:.1f} mm",
                f"  ({row['cross_id']})", f"outside RMS {row['outside_rms_mm']:.2f} mm", f"heat max {mag.max():.1f} mm"]
        for i, t in enumerate(text):
            draw.text((12, y0 + 12 + i * 22), t, fill="white" if i == 0 else "#cfcfcf", font=label_font(19 if i == 0 else 15))
    r.show_heat(None)
    (SEM_OUT / "_tile.png").unlink(missing_ok=True)
    path.parent.mkdir(parents=True, exist_ok=True)
    sheet.save(path)


# --- export hook (used by export_glb) ----------------------------------------------------------


def semantic_targets(gnm: GNM, cfg: dict | None = None) -> list[tuple[str, np.ndarray, np.ndarray]]:
    """[(target name, (V,3) delta at weight 1, (4,3) joint delta at weight 1)] for the BAKED sliders.
    Runtime sliders are mixes of the raw targets and ship in sliders.json instead (sliders_json.py)."""
    cfg = cfg or load_config()
    sol = solve(gnm, cfg)
    ship = shipped_ids(cfg)
    return [(TARGET_PREFIX + sid, sol.delta(gnm, k), sol.joint_delta(gnm, k)) for k, sid in enumerate(sol.ids)
            if sol.baked[k] and sid in ship]


def shipped_ids(cfg: dict) -> set[str]:
    """The sliders the app gets: all but `ship = false` ones (kept in the solver only, so the others still hold their
    measurement exactly as they were solved to)."""
    return {s["id"] for s in cfg["slider"] if s.get("ship", True)}


# --- CLI ------------------------------------------------------------------------------------------------------


def landmarks_main(argv=None) -> None:
    p = argparse.ArgumentParser(description="Propose landmark vertices and render them (out/semantic/landmarks.png).")
    p.add_argument("--write", action="store_true", help="write the proposals into the [landmarks] block of the config")
    p.add_argument("--size", type=int, default=640)
    args = p.parse_args(argv)
    gnm = GNM.load()
    proposed = propose_landmarks(gnm)
    cfg = load_config()
    if args.write or "landmarks" not in cfg:
        write_landmarks(proposed)
        print(f"wrote {len(proposed)} landmarks into {CONFIG.relative_to(PIPELINE_DIR)}")
        cfg = load_config()
    else:
        current = config_landmarks(cfg)
        changed = [n for n, lmk in proposed.items() if n not in current or list(current[n]) != lmk.indices]
        if changed:
            print(f"the config differs from the rules for: {', '.join(changed)} (kept; --write to reset)")
    lm = config_landmarks(cfg)
    for name, ids in lm.items():
        p3 = gnm.template[ids].mean(0) * 1000
        print(f"  {name:18s} {str([int(i) for i in ids])[:40]:40s} x {p3[0]:+6.1f}  y {p3[1]:6.1f}  z {p3[2]:6.1f} mm")
    out = SEM_OUT / "landmarks.png"
    render_landmarks(gnm, lm, cfg, out, args.size)
    print(f"-> {out}")


def report_main(argv=None) -> None:
    p = argparse.ArgumentParser(description="Solve the semantic sliders and write the report + contact sheet.")
    p.add_argument("--no-sheet", action="store_true", help="skip the contact sheet (report only)")
    p.add_argument("--size", type=int, default=300)
    p.add_argument("--check", action="store_true", help="exit 1 unless every slider passes the quality gates below")
    args = p.parse_args(argv)
    t0 = time.time()
    gnm = GNM.load()
    cfg = load_config()
    sol = solve(gnm, cfg)
    t_solve = time.time() - t0
    rows = evaluate(gnm, sol)
    cover = coverage(gnm, sol)
    SEM_OUT.mkdir(parents=True, exist_ok=True)
    np.savez(SEM_OUT / "directions.npz", ids=np.array(sol.ids), components=np.array(sol.components),
             coefficients=sol.coefficients.astype(np.float32))
    (SEM_OUT / "report.json").write_text(json.dumps(rows, indent=1))
    print(write_report(rows, sol, SEM_OUT / "report.md", cover))
    print(f"solved {len(sol.ids)} sliders over {len(sol.components)} components in {t_solve:.1f} s")
    failures = check(rows)
    for f in failures:
        print("FAIL", f)
    print("quality gates:", "PASS" if not failures else f"{len(failures)} failure(s)")
    if not args.no_sheet:
        render_sheet(gnm, sol, cfg, rows, SEM_OUT / "sheet.png", args.size)
        print(f"-> {SEM_OUT / 'sheet.png'}")
    if args.check and failures:
        raise SystemExit(1)
