"""Keep web/src/data/sliders.json (schema v2) in step with the semantic sliders and emotions.

sliders.json is the web panel's contract, organised in panel *sections*:
  identity   the semantic sliders (config/semantic_sliders.toml), one feature each
  emotion    the emotion buttons + intensity (config/emotions.json) and the fine-tune controls
  pose       head and gaze (POSE_SLIDERS below: node rotations, no morph targets)
  advanced   the raw GNM sliders (collapsed in the panel)

Raw sliders are numbered per area ("Head shape 3", "Mouth 12"): every PCA component moves several
features at once, so a single-effect name promises too much. Their names, groups, end labels and
descriptions are generated here (the head ones describe their measured effect); the rest of the entry
from name_sliders.py is kept, with Claude's reading of the renders in `ai.rawName`. Semantic entries and
the emotion list are regenerated from their configs on every run (their names and labels live in those
configs). Runs at the end of `uv run export`, or alone with `uv run update-sliders`.
"""
from __future__ import annotations

import json

import numpy as np

from .age import age_combo, write_ageing_json
from .emotions import CONTROL_PREFIX
from .emotions import TARGET_PREFIX as EMO_PREFIX
from .emotions import load_doc as load_emotions
from .gnm import PIPELINE_DIR, REPO_DIR
from .semantic import TARGET_PREFIX as SEM_PREFIX
from .semantic import load_config as load_semantic

SLIDERS_JSON = REPO_DIR / "web" / "src" / "data" / "sliders.json"
RANGES_JSON = PIPELINE_DIR / "config" / "slider_ranges.json"  # generated by `uv run slider-ranges` (validate/ranges.py)
BREAKS_JSON = PIPELINE_DIR / "config" / "slider_breaks.json"  # generated by `uv run validate --sweep` (validate/sweep.py)
VERSION = 2
SECTIONS = [
    {"id": "identity", "label": "Identity"},
    {"id": "emotion", "label": "Emotion"},
    {"id": "pose", "label": "Pose"},
    {"id": "advanced", "label": "Advanced"},
]
SEMANTIC_GROUPS = {"head": "Head", "face": "Face shape", "jaw_chin": "Jaw & chin", "eyes_brows": "Eyes & brows",
                   "nose": "Nose", "mouth": "Mouth", "ears": "Ears"}
CONTROL_GROUPS = {"mouth": "Mouth", "eyes": "Eyes & brows"}  # under the Expression tab's "Fine-tune" heading
POSE_GROUPS = {"pose_head": "Head", "pose_eyes": "Eyes"}
# Pose (web-only: rotations of the head and eye nodes, lib/pose.ts). Degrees; limits are a comfortable human range
# framed for the camera (neck rotation reaches ~±70° yaw, but the face would leave the portrait).
POSE_SLIDERS = [
    ("pose_head_yaw", "Turn", "pose_head", "left", "right", -35, 35),
    ("pose_head_pitch", "Bend", "pose_head", "forward", "backward", -20, 20),
    ("pose_head_roll", "Tilt", "pose_head", "left", "right", -15, 15),
    ("pose_gaze_yaw", "Look left ↔ right", "pose_eyes", "left", "right", -25, 25),
    ("pose_gaze_pitch", "Look down ↔ up", "pose_eyes", "down", "up", -20, 15),
]
# Raw sliders: GNM region -> (panel group, group label, slider name, what it moves), in panel order. Numbered within
# the region. Head components describe their measured effect instead (raw_description).
RAW_AREAS = {
    "head": ("raw_head", "Head shape", "Head shape", "the head"),
    "lower_face_region": ("raw_mouth", "Mouth", "Mouth", "the lips, jaw and mouth corners"),
    "left_eye_region": ("raw_left_eye", "Left eye", "Left eye", "the left eyelids and brow"),
    "right_eye_region": ("raw_right_eye", "Right eye", "Right eye", "the right eyelids and brow"),
    "eyes": ("raw_eyeballs", "Eyeballs", "Eyeball", "the eyeballs and irises"),
    "pupils": ("raw_eyeballs", "Eyeballs", "Pupils", None),
    "teeth": ("raw_teeth", "Teeth", "Teeth", "the teeth"),
    "tongue": ("raw_tongue", "Tongue", "Tongue", "the tongue"),
}
RAW_EFFECTS = 3  # measured effects listed in a head slider's description
RAW_EFFECT_MIN_MM = 1.0
DEFAULT_INTENSITY = 0.8
MIN_INTENSITY = 0.2  # the slider's "a hint" end: 0 shows no emotion and 0.1 barely any (0.2 → 0.38 at the web's curve 0.6)


def raw_description(sol, component: str, sigma_scale: float) -> str:
    """What a raw head_* slider measurably changes at +1: its largest effects on the semantic measurements."""
    if component not in sol.components:
        return "Moves several features of the head at once."
    mm = sol.J[:, sol.components.index(component)] * sigma_scale  # (S,) mm at weight +1
    top = [k for k in np.argsort(-np.abs(mm) / sol.pop_sigma)[:RAW_EFFECTS] if abs(mm[k]) >= RAW_EFFECT_MIN_MM]
    top.sort(key=lambda k: -abs(mm[k]))  # picked by how unusual the change is, listed by size
    effects = [f"{sol.names[k].lower()} {'+' if mm[k] > 0 else '−'}{abs(mm[k]):.0f} mm" for k in top]
    if not effects:
        return "Moves several features of the head at once, each only slightly."
    return f"Moves several features at once. Largest measured changes toward +: {', '.join(effects)}."


def raw_sliders(doc: dict, sol, sigma_scale: float) -> tuple[list[dict], list[dict]]:
    """The raw sliders renamed per area (see RAW_AREAS), and their panel groups."""
    raw = [s for s in doc["sliders"] if s.get("kind") not in ("semantic", "control", "pose")]
    count: dict[str, int] = {}
    per_region: dict[str, int] = {}
    for s in raw:
        if s["region"] not in RAW_AREAS:
            raise ValueError(f"raw slider {s['id']}: region {s['region']!r} is not one of {list(RAW_AREAS)}")
        per_region[s["region"]] = per_region.get(s["region"], 0) + 1
    for s in raw:
        group, _, name, moves = RAW_AREAS[s["region"]]
        count[s["region"]] = n = count.get(s["region"], 0) + 1
        s["name"] = f"{name} {n}" if per_region[s["region"]] > 1 else name
        s["group"] = group
        s["lowLabel"], s["highLabel"] = "−", "+"
        s["section"] = "advanced"
        s["description"] = (raw_description(sol, s["target"], sigma_scale) if s["region"] == "head"
                            else "Pupil size (a raw component of the head model)." if moves is None
                            else f"A raw component of the head model: moves {moves} together, several things at once.")
    groups = {g: {"id": g, "label": label, "section": "advanced"}
              for region, (g, label, _, _) in RAW_AREAS.items() if region in per_region}
    return raw, list(groups.values())


def apply_ranges(entries: list[dict]) -> int:
    """Each slider's ends (morph weights): the anthropometric ends from `uv run slider-ranges`
    (config/slider_ranges.json), pulled in to just before the face breaks with that slider alone
    (`uv run validate --sweep` and `--ends`, config/slider_breaks.json). The panel shows every two-sided slider as −1 … +1 and scales each half to its own end
    (web lib/morphs/travel.ts)."""
    ranges = json.loads(RANGES_JSON.read_text()) if RANGES_JSON.exists() else {}
    breaks = json.loads(BREAKS_JSON.read_text()) if BREAKS_JSON.exists() else {}
    n = 0
    for e in entries:
        r, b = ranges.get(e["target"]), breaks.get(e["target"], {})
        if r:
            e["min"], e["max"] = float(r["min"]), float(r["max"])
        if "min" in b and b["min"]["end"] > e["min"]:
            e["min"] = float(b["min"]["end"])
        if "max" in b and b["max"]["end"] < e["max"]:
            e["max"] = float(b["max"]["end"])
        if r or b:
            e["min"], e["max"] = round(e["min"], 3), round(e["max"], 3)
            n += 1
    return n


def update(sol, report: list[dict], controls: list[dict], sigma_scale: float) -> dict:
    """Rewrite sliders.json from a semantic.Solution (+ its evaluate() rows) and emotions.solve_controls()."""
    doc = json.loads(SLIDERS_JSON.read_text())
    sem_cfg = load_semantic()
    own_mm = {r["id"]: abs(r["own_mm"]) for r in report}

    raw, raw_groups = raw_sliders(doc, sol, sigma_scale)

    groups = [{"id": "sem_age", "label": "Age", "section": "identity"}]
    groups += [{"id": f"sem_{gid}", "label": label, "section": "identity"} for gid, label in SEMANTIC_GROUPS.items()]
    # Age: a mix of the semantic sliders (config/age.toml); the web app also ages the skin with it (lib/age.ts)
    semantic = [{
        "id": "sem_age", "target": "sem_age", "kind": "semantic", "region": "semantic", "section": "identity",
        "name": "Age", "description": "Younger or older: lips, nose, ears, eyes, brows, cheeks and jowls change the way faces age, and the skin wrinkles from the middle up.",
        "lowLabel": "younger", "highLabel": "older", "group": "sem_age", "min": -1.0, "max": 1.0, "default": 0.0,
        "hidden": False, "combo": age_combo(sol, controls, sigma_scale),
    }]
    for s in sem_cfg["slider"]:
        if not s.get("ship", True):  # solver only (semantic.shipped_ids)
            continue
        if s["group"] not in SEMANTIC_GROUPS:
            raise ValueError(f"semantic slider {s['id']}: group {s['group']!r} is not one of {list(SEMANTIC_GROUPS)}")
        mm = own_mm.get(s["id"])
        extent = f" by about ±{mm:.0f} mm" if mm else ""
        entry = {
            "id": SEM_PREFIX + s["id"], "target": SEM_PREFIX + s["id"], "kind": "semantic", "region": "semantic",
            "section": "identity", "name": s["name"],
            "description": (f"{s['name']}{extent}; the whole head scales with it." if "*" in s.get("free", [])
                            else f"{s['name']}{extent}, keeping the other features where they are."),
            "lowLabel": s.get("low", ""), "highLabel": s.get("high", ""), "group": f"sem_{s['group']}",
            "min": -1.0, "max": 1.0, "default": 0.0, "hidden": False,
        }
        k = sol.ids.index(s["id"])
        if not sol.baked[k]:  # a runtime mix of the raw head_* targets (no morph target of its own)
            entry["combo"] = sol.combo(k, sigma_scale)
        semantic.append(entry)
    groups += [{"id": f"fx_{gid}", "label": label, "section": "emotion"} for gid, label in CONTROL_GROUPS.items()]
    groups += [{"id": gid, "label": label, "section": "pose"} for gid, label in POSE_GROUPS.items()]
    pose = [{
        "id": pid, "target": pid, "kind": "pose", "region": "pose", "section": "pose", "name": name,
        "description": f"{name}: {low} to {high} (degrees, as seen from the front).", "lowLabel": low, "highLabel": high,
        "group": group, "min": float(lo), "max": float(hi), "default": 0.0, "hidden": False, "unit": "deg",
    } for pid, name, group, low, high, lo, hi in POSE_SLIDERS]
    for c in controls:
        combo = c.get("combo") or {c["target"]: 1.0}
        semantic.append({
            "id": CONTROL_PREFIX + c["id"], "target": CONTROL_PREFIX + c["id"], "kind": "control", "region": "control",
            "section": "emotion", "name": c["name"], "description": f"{c['name']}: {c['low']} to {c['high']}.",
            "lowLabel": c["low"], "highLabel": c["high"], "group": f"fx_{c['group']}",
            "min": c["min"], "max": c["max"], "default": 0.0, "hidden": False, "combo": combo,
            **({"comboNeg": c["comboNeg"]} if "comboNeg" in c else {}),
        })

    emo = load_emotions()
    previous = doc.get("emotions", {})
    emotions = {
        "intensity": {**previous.get("intensity", {"max": 1.0, "default": DEFAULT_INTENSITY}), "min": MIN_INTENSITY},
        "items": [
            {"id": eid, "label": rec.get("label", eid.title()), "upper": f"{EMO_PREFIX}{eid}_upper", "lower": f"{EMO_PREFIX}{eid}_lower"}
            for eid, rec in emo["emotions"].items()
        ],
    }

    apply_ranges(semantic + raw)

    out = {
        "version": VERSION,
        "model": doc.get("model"),
        "sigmaScale": doc.get("sigmaScale"),
        "note": ("Everything here is regenerated by `uv run export` / `uv run update-sliders`: raw GNM sliders (section "
                 "advanced) are numbered per area in sliders_json.py (Claude's reading of the renders stays in "
                 "ai.rawName); semantic sliders (section identity) and the emotions list come from "
                 "pipeline/config/semantic_sliders.toml and emotions.json: edit those instead."),
        "sections": SECTIONS,
        "groups": groups + raw_groups,
        "sliders": semantic + pose + raw,
        "emotions": emotions,
    }
    SLIDERS_JSON.write_text(json.dumps(out, indent=2, ensure_ascii=False) + "\n")
    return out


def main() -> None:
    from .emotions import solve_controls
    from .export_glb import load_config as load_components
    from .gnm import GNM
    from .random_split import write as write_random
    from .semantic import evaluate, solve

    gnm = GNM.load()
    sol = solve(gnm, load_semantic())
    sigma_scale = float(load_components()["export"]["sigma_scale"])
    out = update(sol, evaluate(gnm, sol), solve_controls(gnm), sigma_scale)
    write_ageing_json(gnm)
    rs = write_random(gnm, sol, sigma_scale)
    print(f"random.json: Feature sliders carry {rs['features_share'] * 100:.0f}% of a random face; "
          f"split error {rs['rms_error_mm']:.2f} mm RMS ({rs['max_error_mm']:.2f} mm max)")
    kinds = [s["kind"] for s in out["sliders"]]
    n_mix = sum(1 for s in out["sliders"] if s["kind"] == "semantic" and "combo" in s)
    print(f"sliders.json v{VERSION}: {kinds.count('semantic')} semantic ({n_mix} runtime mixes), {kinds.count('control')} fine-tune "
          f"controls, {kinds.count('pose')} pose, {len(kinds) - kinds.count('semantic') - kinds.count('control') - kinds.count('pose')} raw sliders, "
          f"{len(out['emotions']['items'])} emotions -> {SLIDERS_JSON.relative_to(REPO_DIR)}")
