/**
 * LICENCE-AND-CREDITS.md for one exported character: what it wears, the licence of each piece, and what that allows.
 * Pure (plain data in, text out) so the rules are unit-tested; lib/export/files.ts feeds it the live look.
 *
 * Rules (see NOTICE):
 *   head shape  GNM Head, Apache-2.0: commercial use fine, keep the notice
 *   hair        HairCS pack: CC BY-NC 4.0 (non-commercial) · Bystedt grooms: CC BY-SA 4.0 (share alike) · our grooms: MIT
 *   add-ons     generated by our pipeline: MIT (their index says so; anything else is treated as unknown)
 *   unknown     treated as non-commercial, so a new asset can never be exported as "free to sell" by accident
 * The voice parts have their own section: they don't change what the face may be used for.
 */

export type Use = "commercial" | "share-alike" | "non-commercial";

export interface Piece {
  part: string; // "Hair: Long curtain-parted cut"
  licence: string; // "CC BY-NC 4.0"
  url: string;
  credit: string; // attribution text, ready to copy
  use: Use;
}

const LICENCES = {
  apache: { licence: "Apache License 2.0", url: "https://www.apache.org/licenses/LICENSE-2.0" },
  mit: { licence: "MIT", url: "https://opensource.org/license/mit" },
  byNc: { licence: "CC BY-NC 4.0", url: "https://creativecommons.org/licenses/by-nc/4.0/" },
  bySa: { licence: "CC BY-SA 4.0", url: "https://creativecommons.org/licenses/by-sa/4.0/" },
  cc0: { licence: "CC0 1.0", url: "https://creativecommons.org/publicdomain/zero/1.0/" },
};

export const HEAD_PIECE: Piece = {
  part: "Head shape (GNM Head)",
  ...LICENCES.apache,
  credit:
    "Face shape from GNM Head (Generative aNthropometric Model) v3, Copyright 2026 Google LLC, Apache License 2.0, " +
    "https://github.com/google/GNM. Modified by Face to Voice: a selection of its identity and expression components, " +
    "derived semantic and emotion targets, posed and rendered.",
  use: "commercial",
};

export const SKIN_PIECE: Piece = {
  part: "Skin, eyes and lighting",
  ...LICENCES.mit,
  credit: "Skin maps, eye shading and lighting by Face to Voice (MIT).",
  use: "commercial",
};

/** The hair a character wears (null = no hair). `author` and `pack` come from public/models/hair/index.json. */
export function hairPiece(style: { label: string; author: string; pack: string } | null): Piece | null {
  if (!style) return null;
  const part = `Hair: ${style.label}`;
  if (style.pack === "haircs")
    return {
      part,
      ...LICENCES.byNc,
      credit:
        "Hair derived from the HairCS dataset (Lu, Wang, Shen, Zheng, Jiang, Yin Yang, Kui Wu, 2026, arXiv:2609.16465, " +
        "https://huggingface.co/datasets/HairCS2027/HairCS), CC BY-NC 4.0. Modified by Face to Voice: refitted to the GNM " +
        "head, cleaned, resampled and rendered.",
      use: "non-commercial",
    };
  if (/bystedt/i.test(style.author))
    return {
      part,
      ...LICENCES.bySa,
      credit:
        "Hair from \"Hair Styles\" by Daniel Bystedt (Blender demo files, https://www.blender.org/download/demo-files/), " +
        "CC BY-SA 4.0. Modified by Face to Voice: refitted to the GNM head, resampled and rendered.",
      use: "share-alike",
    };
  if (style.pack === "groom" && /face to voice/i.test(style.author))
    return { part, ...LICENCES.mit, credit: "Hair grown procedurally by Face to Voice (MIT).", use: "commercial" };
  return unknown(part, style.author);
}

/** An add-on (brows, lashes, facial hair, glasses). `categoryLicence` is the `licence` line of its index.json. */
export function addonPiece(category: string, style: { label: string; author: string }, categoryLicence: string): Piece {
  const part = `${category}: ${style.label}`;
  if (/^MIT\b/.test(categoryLicence)) return { part, ...LICENCES.mit, credit: `${category} generated by Face to Voice (MIT).`, use: "commercial" };
  return unknown(part, style.author);
}

function unknown(part: string, author: string): Piece {
  return { part, licence: "unknown", url: "", credit: `${part}, by ${author || "unknown"}: licence not recorded, so treated as non-commercial.`, use: "non-commercial" };
}

/** What the whole face allows: the most restrictive piece wins. */
export function overallUse(pieces: Piece[]): Use {
  if (pieces.some((p) => p.use === "non-commercial")) return "non-commercial";
  if (pieces.some((p) => p.use === "share-alike")) return "share-alike";
  return "commercial";
}

const USE_TEXT: Record<Use, string> = {
  commercial: "**Commercial use: yes.** Every piece of this face allows commercial use. Keep the credits below with it.",
  "share-alike":
    "**Commercial use: yes, share alike.** The hair is CC BY-SA 4.0: you may use the portrait commercially, but anything you " +
    "make from it must be shared under CC BY-SA 4.0 too, with the credits below.",
  "non-commercial":
    "**Commercial use: no.** At least one piece (usually the hair) is non-commercial only. For a face you can use commercially, " +
    "rebuild the character with no hair or a hairstyle marked \"Face to Voice\" or \"Bystedt\", and export again.",
};

/**
 * What visitors may do with the voice sample. Face to Voice owns the ElevenLabs Output of its paid plan (ElevenLabs Terms
 * 4(c)(ii)) and passes on the conditions ElevenLabs sets (Prohibited Use Policy §5 and §9).
 */
const VOICE_SAMPLE_TERMS = [
  "You may use voice-sample in your own projects, including commercial ones, on these conditions:",
  "- It is an AI-generated voice (ElevenLabs Voice Design). Don't present it as a real person's voice, and say it is AI-generated wherever listeners could be misled.",
  "- Don't use it to clone a voice or to train, fine-tune or test any AI model (ElevenLabs Prohibited Use Policy, section 9).",
];

export function licenceMarkdown(input: { name: string; pieces: Piece[]; appUrl: string; date: string; hasSample: boolean }): string {
  const { name, pieces, appUrl, date, hasSample } = input;
  const use = overallUse(pieces);
  const rows = pieces.map((p) => `| ${p.part} | ${p.url ? `[${p.licence}](${p.url})` : p.licence} | ${p.use} |`);
  return [
    `# Licence and credits: ${name}`,
    "",
    `Exported from Face to Voice (${appUrl}) on ${date}. A summary, not legal advice: the linked licences are what apply.`,
    "",
    "## The face (portrait.png, character.json, the rebuild link)",
    "",
    USE_TEXT[use],
    "",
    "| Piece | Licence | Use |",
    "| --- | --- | --- |",
    ...rows,
    "",
    "### Credits (copy these next to the image)",
    "",
    ...pieces.map((p) => `- ${p.credit}`),
    "",
    "## The voice",
    "",
    ...(hasSample ? ["### voice-sample", "", ...VOICE_SAMPLE_TERMS, ""] : []),
    "### voice.md and voice.json",
    "",
    `The prompt, casting and settings are released under [${LICENCES.cc0.licence}](${LICENCES.cc0.url}): use them however you like.`,
    "A voice you design from them in your own ElevenLabs account is your own Output, under your ElevenLabs plan's terms",
    "(paid plans allow commercial use).",
    "",
    "## Fonts",
    "",
    "No text is drawn into these files, so no font licence applies.",
    "",
  ].join("\n");
}
